// Media Storm in Vietnamese. Loaded before mediaStorm.js; the English text as shown is the key.
// Patterns catch texts with numbers or names ($1, $2 … = the parts in brackets, translated too if they
// are in `texts`). The language follows Stash UI's choice, otherwise Stash's interface language.
(function () {
  window.MediaStormLocales = window.MediaStormLocales || {};
  window.MediaStormLocales["vi"] = {
    sep: ", ",
    texts: {
      "Media Storm": "Media Storm",
      "Storm": "Storm",
      "Ready": "Sẵn sàng",
      "Running": "Đang chạy",
      "Paused": "Đã tạm dừng",
      "Stopped": "Đã dừng",
      "starts in its own tab": "bắt đầu trong tab riêng",
      "Running in the storm tab": "Đang chạy trong tab storm",
      "Start": "Bắt đầu",
      "Stop": "Dừng",
      "Restart": "Khởi động lại",
      "Pause": "Tạm dừng",
      "Pause / resume": "Tạm dừng / tiếp tục",
      "Pause / resume (Space)": "Tạm dừng / tiếp tục (Space)",
      "Next wave": "Đợt tiếp theo",
      "Next wave now (N)": "Đợt tiếp theo ngay (N)",
      "Next wave right away": "Đợt tiếp theo ngay lập tức",
      "New wave": "Đợt mới",
      "Reroll background": "Đổi nền khác",
      "Reroll background (B)": "Đổi nền khác (B)",
      "Close (Esc)": "Đóng (Esc)",
      "Close panel": "Đóng bảng",
      "Stop (Esc)": "Dừng (Esc)",
      "Settings (S)": "Cài đặt (S)",
      "Settings": "Cài đặt",
      "Fullscreen (F)": "Toàn màn hình (F)",
      "Fullscreen": "Toàn màn hình",
      "Fullscreen not allowed": "Không được phép toàn màn hình",
      "Liquid glass": "Kính lỏng",
      "Back": "Quay lại",
      "Back to the overview (Esc)": "Quay lại tổng quan (Esc)",
      "Hotkeys & mouse": "Phím tắt và chuột",
      "Expand/collapse": "Mở rộng/thu gọn",
      "Click or press a key for sound": "Nhấp hoặc nhấn phím để có âm thanh",
      "A freshly opened storm tab may only play sound after a click or key press.": "Tab storm vừa mở có thể chỉ phát âm thanh sau khi nhấp hoặc nhấn phím.",
      "Nothing found": "Không tìm thấy gì",
      "With these filters there are no images or videos. Loosen tags, folders or rating – or reset everything.": "Với các bộ lọc này không có hình ảnh hay video nào. Hãy nới lỏng thẻ, thư mục hoặc xếp hạng – hoặc đặt lại mọi thứ.",
      "Reset filters": "Đặt lại bộ lọc",
      "Filters reset – whole library": "Đã đặt lại bộ lọc – toàn bộ thư viện",
      "No media found for this source/filter": "Không tìm thấy phương tiện nào cho nguồn/bộ lọc này",
      "First wave loading …": "Đang tải đợt đầu tiên …",
      "Searching …": "Đang tìm …",
      "Error while loading:": "Lỗi khi tải:",
      "Background error:": "Lỗi nền:",
      "GraphQL error:": "Lỗi GraphQL:",
      "Pop-up blocked – please allow pop-ups for Stash": "Cửa sổ bật lên bị chặn – hãy cho phép cửa sổ bật lên cho Stash",
      "Mood": "Tâm trạng",
      "Next mood": "Tâm trạng tiếp theo",
      "Default": "Mặc định",
      "Chaos as usual": "Hỗn loạn như mọi khi",
      "Chill": "Thư giãn",
      "Pile, calm, breathing": "Chồng lên, êm dịu, như đang thở",
      "Fast, full, shaking": "Nhanh, đầy ắp, rung lắc",
      "Gallery": "Phòng tranh",
      "Mosaic, tidy": "Khảm, ngăn nắp",
      "Cinema": "Rạp chiếu",
      "Spotlight, videos only": "Tâm điểm, chỉ video",
      "Trip": "Ảo giác",
      "Spiral, colors, 3D": "Xoắn ốc, màu sắc, 3D",
      "Ticker": "Băng chữ chạy",
      "Polaroids drift by": "Ảnh Polaroid trôi qua",
      "Rain": "Mưa",
      "Falls through from the top": "Rơi từ trên xuống",
      "Manga": "Manga",
      "Ink, halftone, impact": "Mực, bán sắc, va đập",
      "Neon": "Neon",
      "Glow, glitch, beat": "Phát sáng, nhiễu loạn, nhịp",
      "Tempo": "Nhịp độ",
      "On the beat": "Theo nhịp",
      "Media": "Phương tiện",
      "Sound": "Âm thanh",
      "Layout": "Bố cục",
      "Layout:": "Bố cục:",
      "Effects": "Hiệu ứng",
      "Background": "Nền",
      "Source & filters": "Nguồn và bộ lọc",
      "Folders": "Thư mục",
      "RedGifs": "RedGifs",
      "My presets": "Bộ cài sẵn của tôi",
      "New wave every": "Đợt mới mỗi",
      "Every": "Mỗi",
      "Items per wave": "Số mục mỗi đợt",
      "First wave (right away)": "Đợt đầu tiên (ngay lập tức)",
      "At most at once": "Tối đa cùng lúc",
      "Items / Maximum": "Mục / Tối đa",
      "Endless – replace the oldest items instead of stopping": "Vô tận – thay các mục cũ nhất thay vì dừng",
      "Waves on the beat of a song": "Các đợt theo nhịp của một bài hát",
      "Choose song …": "Chọn bài hát …",
      "No song yet": "Chưa có bài hát",
      "No song chosen": "Chưa chọn bài hát",
      "Song volume": "Âm lượng bài hát",
      "Every 2 beats": "Mỗi 2 nhịp",
      "Every bar (4 beats)": "Mỗi ô nhịp (4 nhịp)",
      "Every 2 bars": "Mỗi 2 ô nhịp",
      "On every beat": "Mỗi nhịp",
      "Couldn't save the song (storage blocked?)": "Không lưu được bài hát (bộ nhớ bị chặn?)",
      "On the beat: click or press a key to start the music": "Theo nhịp: nhấp hoặc nhấn phím để bắt đầu nhạc",
      "On the beat: couldn't read the song": "Theo nhịp: không đọc được bài hát",
      "On the beat: no song chosen yet (panel → On the beat) – waves run by time": "Theo nhịp: chưa chọn bài hát (bảng → Theo nhịp) – các đợt chạy theo thời gian",
      "Images": "Hình ảnh",
      "Videos": "Video",
      "Mix": "Trộn",
      "Video source": "Nguồn video",
      "Full video": "Toàn bộ video",
      "Preview clip (lighter)": "Clip xem trước (nhẹ hơn)",
      "Image quality": "Chất lượng hình ảnh",
      "Thumbnail (faster)": "Ảnh thu nhỏ (nhanh hơn)",
      "Original": "Gốc",
      "Random start": "Bắt đầu ngẫu nhiên",
      "Random start point in the video": "Điểm bắt đầu ngẫu nhiên trong video",
      "Ken Burns zoom on images": "Phóng to kiểu Ken Burns cho hình ảnh",
      "Volume": "Âm lượng",
      "Audible": "Có tiếng",
      "all videos": "tất cả video",
      "All videos": "Tất cả video",
      "under the mouse": "dưới con trỏ chuột",
      "Only under the mouse": "Chỉ dưới con trỏ chuột",
      "newest video": "video mới nhất",
      "Only the newest video": "Chỉ video mới nhất",
      "muted": "tắt tiếng",
      "Muted": "Tắt tiếng",
      "Automatic by loudness": "Tự động theo độ to",
      "Chaos": "Hỗn loạn",
      "Pile": "Chồng",
      "Grid": "Lưới",
      "Mosaic": "Khảm",
      "Spotlight": "Tâm điểm",
      "Spiral": "Xoắn ốc",
      "Scattered everywhere. Drag to move, mouse wheel to scale.": "Rải rác khắp nơi. Kéo để di chuyển, con lăn chuột để đổi cỡ.",
      "Like photos on a table, heaped towards the middle.": "Như ảnh trên bàn, chất đống về phía giữa.",
      "Fixed cells that fill the whole screen.": "Các ô cố định lấp đầy cả màn hình.",
      "Pinboard columns: new items come in at the top, the rest slides down.": "Các cột bảng ghim: mục mới vào ở trên cùng, phần còn lại trượt xuống.",
      "The newest item big in the middle, the older ones in a circle around it.": "Mục mới nhất to ở giữa, các mục cũ hơn xếp vòng tròn quanh nó.",
      "Sunflower spiral with the newest item in the middle – every wave turns everything further.": "Xoắn ốc hoa hướng dương với mục mới nhất ở giữa – mỗi đợt xoay mọi thứ thêm nữa.",
      "Lanes from right to left. Items that have passed make room for new ones.": "Các làn từ phải sang trái. Mục đã đi qua nhường chỗ cho mục mới.",
      "Falls through from the top. At the bottom, items make room for new ones.": "Rơi từ trên xuống. Ở dưới cùng, các mục nhường chỗ cho mục mới.",
      "Avoid overlap – free spots first": "Tránh chồng chéo – chỗ trống trước",
      "Size min": "Cỡ nhỏ nhất",
      "Size max": "Cỡ lớn nhất",
      "Rotation": "Xoay",
      "Spacing": "Khoảng cách",
      "Columns": "Cột",
      "Speed": "Tốc độ",
      "Frame": "Khung",
      "Soft": "Mềm",
      "None": "Không",
      "Polaroid": "Polaroid",
      "Circle": "Tròn",
      "Square": "Vuông",
      "Shape": "Hình dạng",
      "Format": "Định dạng",
      "Landscape 16:9": "Ngang 16:9",
      "Portrait 3:4": "Dọc 3:4",
      "Appear": "Xuất hiện",
      "Zoom": "Phóng to",
      "Fade in": "Hiện dần",
      "Fade in and out": "Hiện dần và mờ dần",
      "Slam": "Đập vào",
      "Flip": "Lật",
      "Fall": "Rơi",
      "Spin": "Xoay tròn",
      "Glitch start": "Bắt đầu nhiễu loạn",
      "Motion": "Chuyển động",
      "Drift": "Trôi",
      "Breathe": "Thở",
      "Wobble": "Lắc lư",
      "Hold still": "Giữ yên",
      "Pulse": "Nhịp đập",
      "Color rush": "Dải màu dồn dập",
      "Glitch": "Nhiễu loạn",
      "Blending": "Trộn",
      "Normal": "Bình thường",
      "Double exposure": "Phơi sáng kép",
      "Negative": "Âm bản",
      "Negative rush": "Dồn dập âm bản",
      "Texture": "Kết cấu",
      "Film grain": "Hạt phim",
      "Halftone": "Bán sắc",
      "Vignette": "Tối góc",
      "3D depth – parallax with the mouse": "Chiều sâu 3D – hiệu ứng thị sai theo chuột",
      "Reflection": "Phản chiếu",
      "Reflection under every item": "Phản chiếu dưới mỗi mục",
      "Shake": "Rung lắc",
      "Flash": "Chớp sáng",
      "The flash is gentle and comes at most once per wave.": "Chớp sáng nhẹ nhàng và chỉ xuất hiện nhiều nhất một lần mỗi đợt.",
      "Just zoom and fade": "Chỉ phóng to và mờ dần",
      "Darken": "Làm tối",
      "Blur": "Làm mờ",
      "soft": "nhẹ",
      "rerolls itself": "tự đổi",
      "New background": "Nền mới",
      "Reroll automatically": "Tự động đổi",
      "On every new wave": "Ở mỗi đợt mới",
      "Artwork in the design": "Tác phẩm nghệ thuật trong thiết kế",
      "Show images in the panel and at the start": "Hiện hình ảnh trong bảng và lúc bắt đầu",
      "e.g. Artwork": "ví dụ: Artwork",
      "Uses images and scene screenshots with this tag and from folders with the same name. Click the cover for the next image.": "Dùng hình ảnh và ảnh chụp màn hình cảnh có thẻ này và từ các thư mục cùng tên. Nhấp vào ảnh bìa để sang hình tiếp theo.",
      "Next image": "Hình tiếp theo",
      "No background images found (tag “background”)": "Không tìm thấy hình nền (thẻ “background”)",
      "The Random Backgrounds plugin is not active": "Plugin Random Backgrounds chưa hoạt động",
      "plugin not active": "plugin chưa hoạt động",
      "Source": "Nguồn",
      "Whole library": "Toàn bộ thư viện",
      "Current page": "Trang hiện tại",
      "Current page (performer/tag/…)": "Trang hiện tại (diễn viên/thẻ/…)",
      "“Current page” uses the performer, tag, studio, gallery or group page you start from. On tag pages, your own tags always all have to match.": "“Trang hiện tại” dùng trang diễn viên, thẻ, hãng phim, thư viện ảnh hoặc nhóm mà bạn bắt đầu từ đó. Trên trang thẻ, các thẻ của riêng bạn đều phải khớp.",
      "Not a performer/tag/studio/gallery/group page – using the whole library": "Không phải trang diễn viên/thẻ/hãng phim/thư viện ảnh/nhóm – dùng toàn bộ thư viện",
      "Only with tags": "Chỉ với các thẻ",
      "Exclude tags": "Loại trừ thẻ",
      "Marker clips": "Clip dấu mốc",
      "Marker clips are the short moments you marked in your scenes. This share of the videos plays them (only the marked part, looping) instead of whole scenes. Choose which markers under Source & filters.": "Clip dấu mốc là những khoảnh khắc ngắn bạn đã đánh dấu trong cảnh. Tỷ lệ video này phát chúng (chỉ phần được đánh dấu, lặp lại) thay vì cả cảnh. Chọn dấu mốc nào trong Nguồn và bộ lọc.",
      "Only marker clips with tags": "Chỉ clip dấu mốc có thẻ",
      "Needs a share of marker clips under Media. Primary or extra tag of the marker; the filters above apply to the marker's scene.": "Cần một tỷ lệ clip dấu mốc trong Phương tiện. Thẻ chính hoặc thẻ phụ của dấu mốc; các bộ lọc ở trên áp dụng cho cảnh của dấu mốc.",
      "All tags must match": "Mọi thẻ đều phải khớp",
      "Including sub-tags (recursive)": "Bao gồm thẻ con (đệ quy)",
      "On tag pages, all chosen tags must match": "Trên trang thẻ, mọi thẻ đã chọn đều phải khớp",
      "Minimum rating": "Xếp hạng tối thiểu",
      "Only with favorite performers": "Chỉ với diễn viên yêu thích",
      "favorites": "yêu thích",
      "Search tag…": "Tìm thẻ…",
      "No tags found": "Không tìm thấy thẻ",
      "A playlist (from Stash UI)": "Một danh sách phát (từ Stash UI)",
      "Playlist": "Danh sách phát",
      "A playlist": "Một danh sách phát",
      "No playlists yet": "Chưa có danh sách phát",
      "Stash UI's smart playlists: set filters in Scenes or Images there and press “Save as playlist”. The playlist decides – the filters below don't apply.": "Danh sách phát thông minh của Stash UI: đặt bộ lọc ở Cảnh hoặc Hình ảnh trong đó rồi nhấn “Lưu làm danh sách phát”. Danh sách phát quyết định – các bộ lọc bên dưới không áp dụng.",
      "Only with performers": "Chỉ với các diễn viên",
      "All performers must be in it": "Mọi diễn viên đều phải có mặt",
      "Search performer…": "Tìm diễn viên…",
      "No performers found": "Không tìm thấy diễn viên",
      "Resolution up to": "Độ phân giải tối đa",
      "Videos at least": "Video tối thiểu",
      "any length": "mọi độ dài",
      "1 min": "1 phút",
      "5 min": "5 phút",
      "20 min": "20 phút",
      "A lower resolution runs smoother – 4K videos take the most.": "Độ phân giải thấp hơn chạy mượt hơn – video 4K nặng nhất.",
      "All folders": "Tất cả thư mục",
      "Filter folders…": "Lọc thư mục…",
      "Loading folders…": "Đang tải thư mục…",
      "No folders found": "Không tìm thấy thư mục",
      "Without a choice, the whole library is used. Subfolders are always included. Numbers: images (I) and videos (V).": "Nếu không chọn, dùng toàn bộ thư viện. Thư mục con luôn được bao gồm. Các số: hình ảnh (I) và video (V).",
      "RedGifs share": "Tỷ lệ RedGifs",
      "Niches, tags & creators": "Ngách, thẻ & người sáng tạo",
      "Search niches, tags, creators …": "Tìm ngách, thẻ, người sáng tạo …",
      "Niche": "Ngách",
      "Niches": "Ngách",
      "Tag": "Thẻ",
      "Tags": "Thẻ",
      "Creator": "Người sáng tạo",
      "Verified": "Đã xác minh",
      "Trending": "Thịnh hành",
      "Top of the week": "Hàng đầu trong tuần",
      "Top of the month": "Hàng đầu trong tháng",
      "Top (all time)": "Hàng đầu (mọi thời điểm)",
      "Latest": "Mới nhất",
      "Sort order": "Thứ tự sắp xếp",
      "Quality": "Chất lượng",
      "Saving (⬇ on hover or key D)": "Lưu (⬇ khi di chuột hoặc phím D)",
      "Save location": "Nơi lưu",
      "Everything in one folder": "Tất cả trong một thư mục",
      "By source (niche/tag/creator)": "Theo nguồn (ngách/thẻ/người sáng tạo)",
      "By the clip's creator": "Theo người sáng tạo của clip",
      "Always saved in HD. If the save location is inside your Stash library, Stash scans the folder right away and the scene gets the link, title and the tag “RedGifs”.": "Luôn lưu ở chất lượng HD. Nếu nơi lưu nằm trong thư viện Stash, Stash quét thư mục ngay và cảnh nhận được liên kết, tiêu đề và thẻ “RedGifs”.",
      "Save the RedGifs clip under the mouse to Stash": "Lưu clip RedGifs dưới con trỏ chuột vào Stash",
      "Hover over a RedGifs clip, then press D": "Di chuột lên clip RedGifs rồi nhấn D",
      "Save to Stash (D)": "Lưu vào Stash (D)",
      "Open in Stash or on RedGifs": "Mở trong Stash hoặc trên RedGifs",
      "Open in Stash (Ctrl+click)": "Mở trong Stash (Ctrl+nhấp)",
      "Open on RedGifs (Ctrl+click)": "Mở trên RedGifs (Ctrl+nhấp)",
      "Already saved": "Đã lưu rồi",
      "Already there": "Đã có sẵn",
      "Saved": "Đã lưu",
      "Saved – Stash is still scanning, the scene will appear shortly": "Đã lưu – Stash vẫn đang quét, cảnh sẽ sớm xuất hiện",
      "Saved, but importing into Stash failed:": "Đã lưu, nhưng nhập vào Stash thất bại:",
      "Download failed:": "Tải xuống thất bại:",
      "Failed – try again": "Thất bại – hãy thử lại",
      "Authentication failed": "Xác thực thất bại",
      "creator not found": "không tìm thấy người sáng tạo",
      "not found": "không tìm thấy",
      "no Stash library configured": "chưa cấu hình thư viện Stash",
      "no answer from the plugin backend": "backend plugin không phản hồi",
      "Preset": "Bộ cài sẵn",
      "Name for a new preset": "Tên cho bộ cài sẵn mới",
      "A preset of your own saves all settings, including source, filters and RedGifs.": "Bộ cài sẵn của riêng bạn lưu mọi cài đặt, gồm nguồn, bộ lọc và RedGifs.",
      "Save": "Lưu",
      "Load": "Tải",
      "Delete": "Xóa",
      "None yet": "Chưa có",
      "Reset everything to defaults": "Đặt lại mọi thứ về mặc định",
      "Settings reset": "Đã đặt lại cài đặt",
      "Sleep timer": "Hẹn giờ ngủ",
      "Sleep timer ran out – good night": "Hẹn giờ ngủ đã hết – chúc ngủ ngon",
      "The sleep timer stops with a fade-out and closes the storm tab.": "Hẹn giờ ngủ dừng bằng hiệu ứng mờ dần và đóng tab storm.",
      "Afterwards": "Sau đó",
      "This panel": "Bảng này",
      "Show the HUD in the storm tab": "Hiện HUD trong tab storm",
      "Show item big": "Hiện mục lớn",
      "Remove item": "Gỡ mục",
      "Remove (right-click)": "Gỡ (nhấp chuột phải)",
      "Remove all items": "Gỡ mọi mục",
      "Stop everything (with fade-out)": "Dừng mọi thứ (có mờ dần)",
      "Change layout": "Đổi bố cục",
      "Move item (chaos, pile)": "Di chuyển mục (hỗn loạn, chồng)",
      "Scale item (chaos, pile)": "Đổi cỡ mục (hỗn loạn, chồng)",
      "Click": "Nhấp",
      "Ctrl+click": "Ctrl+nhấp",
      "Right-click": "Nhấp chuột phải",
      "Drag": "Kéo",
      "Mouse wheel": "Con lăn chuột",
      "Space": "Space",
      "Volume ±5": "Âm lượng ±5",
      "Remove": "Gỡ",
      "Unknown": "Không rõ",
      "Off": "Tắt",
      "off": "tắt",
      "auto": "tự động",
      "Max": "Tối đa",
      "Mixed": "Hỗn hợp",
      "Random": "Ngẫu nhiên",
      "Performer": "Diễn viên",
      "Studio": "Hãng phim",
      "Group": "Nhóm",
      "Scene": "Cảnh",
      "Image": "Hình ảnh",
      "Tag or folder": "Thẻ hoặc thư mục",
      "preview clips": "clip xem trước",
      "endless": "vô tận",
      "The storm tab detects tempo and beats itself (a few seconds per song), and the song loops. New items load ahead and appear exactly on the beat. Automatic: calm parts every bar, medium every 2 beats, loud every beat – drops right away. With pulse, the stage pumps on every beat; flash and shake come with the waves. “New wave every” doesn't apply then.": "Tab storm tự dò nhịp độ và nhịp (vài giây mỗi bài), và bài hát lặp lại. Các mục mới được tải trước và xuất hiện đúng nhịp. Tự động: đoạn êm mỗi ô nhịp, vừa mỗi 2 nhịp, to mỗi nhịp – drop thì ngay lập tức. Với nhịp đập, sân khấu đập theo mỗi nhịp; chớp sáng và rung lắc đi cùng các đợt. Khi đó “Đợt mới mỗi” không áp dụng.",
      "Loop videos (off = fade out after the end)": "Lặp lại video (tắt = mờ dần sau khi kết thúc)",
      "Rush": "Dồn dập",
      "any": "bất kỳ",
      "SD (faster)": "SD (nhanh hơn)",
      "HD (sharper)": "HD (nét hơn)",
      "Typing shows matching niches, tags and creators live – click (or ↑/↓ + Enter) to add them. Several are possible; one of them is picked at random per fetch. Without a choice you get trending. RedGifs only plays in the storm tab.": "Khi gõ, các ngách, thẻ và người sáng tạo khớp hiện ra ngay – nhấp (hoặc ↑/↓ + Enter) để thêm. Có thể thêm nhiều; mỗi lần lấy sẽ chọn ngẫu nhiên một trong số đó. Nếu không chọn, bạn nhận mục thịnh hành. RedGifs chỉ phát trong tab storm.",
      "HUD on/off": "Bật/tắt HUD",
      "Full videos at once": "Số video đầy đủ cùng lúc",
      "0 = automatic: Media Storm measures how quickly Stash still answers and plays as many full videos as the connection allows. Over plain HTTP, browsers keep only about 6 connections to one server – when they're all taken, Stash stops answering in this browser. Further videos play as preview clips (or show their cover).": "0 = tự động: Media Storm đo Stash còn phản hồi nhanh đến đâu và phát nhiều video đầy đủ nhất mà kết nối cho phép. Qua HTTP thường, trình duyệt chỉ giữ khoảng 6 kết nối tới một máy chủ – khi tất cả đã bị chiếm, Stash ngừng phản hồi trong trình duyệt này. Các video còn lại phát dưới dạng clip xem trước (hoặc hiện ảnh bìa).",
    },
    patterns: [
      ["Playlist “(.+)”", "Danh sách phát “$1”"],
      ["(.+) \\((scenes|images)\\)", "$1 ($2)"],
      ["up to (\\d+)p", "tối đa $1p"],
      ["≥ (\\d+) min", "≥ $1 phút"],
      ["(\\d+) performers", "$1 diễn viên"],
      ["On the beat (\\d+) new, max (\\d+) endless", "Theo nhịp · $1 mục mới mỗi đợt, tối đa $2 · vô tận"],
      ["On the beat (\\d+) new, max (\\d+)", "Theo nhịp · $1 mục mới mỗi đợt, tối đa $2"],
      ["Every (\\d+) s (\\d+) new, max (\\d+) endless", "Mỗi $1 giây · $2 mục mới mỗi đợt, tối đa $3 · vô tận"],
      ["Every (\\d+) s (\\d+) new, max (\\d+)", "Mỗi $1 giây · $2 mục mới mỗi đợt, tối đa $3"],
      ["(\\d+) % marker clips", "$1 % clip dấu mốc"],
      ["(\\d+) marker tags? \\+sub", "$1 thẻ dấu mốc (gồm thẻ con)"],
      ["(\\d+) marker tags?", "$1 thẻ dấu mốc"],
      ["(\\d+) % of the videos", "$1 % số video"],
      ["(\\d+) % videos, preview clips", "$1 % video, clip xem trước"],
      ["(\\d+) % videos", "$1 % video"],
      ["(\\d+) % images, (\\d+) % videos", "$1 % hình ảnh, $2 % video"],
      ["(\\d+) %, (.+)", "$1 %, $2"],
      ["(.+?), frame (.+)", "$1, khung $2"],
      ["Darkened (\\d+) %(.*)", "Làm tối $1 %$2"],
      ["(\\d+) tags?", "$1 thẻ"],
      ["without (\\d+)", "trừ $1"],
      ["from (★+)", "từ $1"],
      ["(\\d+) saved", "đã lưu $1"],
      ["(\\d+) s", "$1 giây"],
      ["(\\d+) min", "$1 phút"],
      ["level (\\d+)", "cấp $1"],
      ["every (\\d+) waves", "mỗi $1 đợt"],
      ["(\\d+) % of items", "$1 % số mục"],
      ["(\\d+) px/s", "$1 px/giây"],
      ["Volume (\\d+) ?%", "Âm lượng $1%"],
      ["· (\\d+) Clips", "· $1 clip"],
      ["Mood “(.+)”", "Tâm trạng “$1”"],
      ["Preset “(.+)” deleted", "Đã xóa bộ cài sẵn “$1”"],
      ["Preset “(.+)” loaded", "Đã tải bộ cài sẵn “$1”"],
      ["Preset “(.+)” saved", "Đã lưu bộ cài sẵn “$1”"],
      ["Song “(.+)” chosen", "Đã chọn bài hát “$1”"],
      ["On the beat: (.+) BPM", "Theo nhịp: $1 BPM"],
      ["On the beat: detecting beats in “(.+)” …", "Theo nhịp: đang dò nhịp trong “$1” …"],
      ["Imported into Stash ✓ \\((.+?) #(\\d+)\\)", "Đã nhập vào Stash ✓ ($1 #$2)"],
      ["Error while loading: (.+)", "Lỗi khi tải: $1"],
      ["Background error: (.+)", "Lỗi nền: $1"],
      ["Error: (.+)", "Lỗi: $1"],
      ["Download failed: (.+)", "Tải xuống thất bại: $1"],
      ["Saved, but importing into Stash failed: (.+)", "Đã lưu, nhưng nhập vào Stash thất bại: $1"],
      ["GraphQL error: (.+)", "Lỗi GraphQL: $1"],
      ["Media Storm (\\d[\\d.]*)", "Media Storm $1"],
      ["([\\d.,]+) Tsd\\.", "$1 nghìn"],
      ["([\\d.,]+) Mio\\.", "$1 triệu"],
    ],
  };
})();
