// Media Storm in German. Loaded before mediaStorm.js; the English text as shown is the key.
// Patterns catch texts with numbers or names ($1, $2 … = the parts in brackets, translated too if they
// are in `texts`). The language follows Stash UI's choice, otherwise Stash's interface language.
(function () {
  window.MediaStormLocales = window.MediaStormLocales || {};
  window.MediaStormLocales["de"] = {
    sep: ", ",
    texts: {
      "Media Storm": "Media Storm",
      "Storm": "Storm",
      "Ready": "Bereit",
      "Running": "Läuft",
      "Paused": "Pausiert",
      "Stopped": "Gestoppt",
      "starts in its own tab": "startet in einem eigenen Tab",
      "Running in the storm tab": "Läuft im Storm-Tab",
      "Start": "Start",
      "Stop": "Stopp",
      "Restart": "Neustart",
      "Pause": "Pause",
      "Pause / resume": "Pause / fortsetzen",
      "Pause / resume (Space)": "Pause / fortsetzen (Leertaste)",
      "Next wave": "Nächste Welle",
      "Next wave now (N)": "Jetzt nächste Welle (N)",
      "Next wave right away": "Nächste Welle sofort",
      "New wave": "Neue Welle",
      "Reroll background": "Hintergrund neu würfeln",
      "Reroll background (B)": "Hintergrund neu würfeln (B)",
      "Close (Esc)": "Schließen (Esc)",
      "Close panel": "Panel schließen",
      "Stop (Esc)": "Stopp (Esc)",
      "Settings (S)": "Einstellungen (S)",
      "Settings": "Einstellungen",
      "Fullscreen (F)": "Vollbild (F)",
      "Fullscreen": "Vollbild",
      "Fullscreen not allowed": "Vollbild nicht erlaubt",
      "Liquid glass": "Liquid Glass",
      "Back": "Zurück",
      "Back to the overview (Esc)": "Zurück zur Übersicht (Esc)",
      "Hotkeys & mouse": "Hotkeys & Maus",
      "Expand/collapse": "Aus-/Einklappen",
      "Click or press a key for sound": "Klicken oder eine Taste drücken für Ton",
      "A freshly opened storm tab may only play sound after a click or key press.": "Ein frisch geöffneter Storm-Tab spielt Ton unter Umständen erst nach einem Klick oder Tastendruck.",
      "Nothing found": "Nichts gefunden",
      "With these filters there are no images or videos. Loosen tags, folders or rating – or reset everything.": "Mit diesen Filtern gibt es keine Bilder oder Videos. Lockere Tags, Ordner oder Bewertung – oder setze alles zurück.",
      "Reset filters": "Filter zurücksetzen",
      "Filters reset – whole library": "Filter zurückgesetzt – ganze Bibliothek",
      "No media found for this source/filter": "Keine Medien für diese Quelle/diesen Filter gefunden",
      "First wave loading …": "Erste Welle lädt …",
      "Searching …": "Suche …",
      "Error while loading:": "Fehler beim Laden:",
      "Background error:": "Hintergrundfehler:",
      "GraphQL error:": "GraphQL-Fehler:",
      "Pop-up blocked – please allow pop-ups for Stash": "Pop-up blockiert – bitte Pop-ups für Stash erlauben",
      "Mood": "Stimmung",
      "Next mood": "Nächste Stimmung",
      "Default": "Standard",
      "Chaos as usual": "Chaos wie immer",
      "Chill": "Chill",
      "Pile, calm, breathing": "Stapel, ruhig, atmend",
      "Fast, full, shaking": "Schnell, voll, wackelnd",
      "Gallery": "Galerie",
      "Mosaic, tidy": "Mosaik, aufgeräumt",
      "Cinema": "Kino",
      "Spotlight, videos only": "Spotlight, nur Videos",
      "Trip": "Trip",
      "Spiral, colors, 3D": "Spirale, Farben, 3D",
      "Ticker": "Ticker",
      "Polaroids drift by": "Polaroids ziehen vorbei",
      "Rain": "Regen",
      "Falls through from the top": "Fällt von oben herab",
      "Manga": "Manga",
      "Ink, halftone, impact": "Tusche, Halbton, Wucht",
      "Neon": "Neon",
      "Glow, glitch, beat": "Glow, Glitch, Beat",
      "Tempo": "Tempo",
      "On the beat": "Im Beat",
      "Media": "Medien",
      "Sound": "Ton",
      "Layout": "Layout",
      "Layout:": "Layout:",
      "Effects": "Effekte",
      "Background": "Hintergrund",
      "Source & filters": "Quelle & Filter",
      "Folders": "Ordner",
      "RedGifs": "RedGifs",
      "My presets": "Meine Presets",
      "New wave every": "Neue Welle alle",
      "Every": "Alle",
      "Items per wave": "Elemente pro Welle",
      "First wave (right away)": "Erste Welle (sofort)",
      "At most at once": "Höchstens gleichzeitig",
      "Items / Maximum": "Elemente / Maximum",
      "Endless – replace the oldest items instead of stopping": "Endlos – ersetzt die ältesten Elemente, statt zu stoppen",
      "Waves on the beat of a song": "Wellen im Beat eines Songs",
      "Choose song …": "Song wählen …",
      "No song yet": "Noch kein Song",
      "No song chosen": "Kein Song gewählt",
      "Song volume": "Song-Lautstärke",
      "Every 2 beats": "Alle 2 Beats",
      "Every bar (4 beats)": "Jeder Takt (4 Beats)",
      "Every 2 bars": "Alle 2 Takte",
      "On every beat": "Bei jedem Beat",
      "Couldn't save the song (storage blocked?)": "Song konnte nicht gespeichert werden (Speicher blockiert?)",
      "On the beat: click or press a key to start the music": "Im Beat: klicken oder eine Taste drücken, um die Musik zu starten",
      "On the beat: couldn't read the song": "Im Beat: Song konnte nicht gelesen werden",
      "On the beat: no song chosen yet (panel → On the beat) – waves run by time": "Im Beat: noch kein Song gewählt (Panel → Im Beat) – Wellen laufen nach Zeit",
      "Images": "Bilder",
      "Videos": "Videos",
      "Mix": "Mix",
      "Video source": "Videoquelle",
      "Full video": "Ganzes Video",
      "Preview clip (lighter)": "Vorschau-Clip (leichter)",
      "Image quality": "Bildqualität",
      "Thumbnail (faster)": "Vorschaubild (schneller)",
      "Original": "Original",
      "Random start": "Zufälliger Start",
      "Random start point in the video": "Zufälliger Startpunkt im Video",
      "Ken Burns zoom on images": "Ken-Burns-Zoom bei Bildern",
      "Volume": "Lautstärke",
      "Audible": "Hörbar",
      "all videos": "alle Videos",
      "All videos": "Alle Videos",
      "under the mouse": "unter der Maus",
      "Only under the mouse": "Nur unter der Maus",
      "newest video": "neuestes Video",
      "Only the newest video": "Nur das neueste Video",
      "muted": "stumm",
      "Muted": "Stumm",
      "Automatic by loudness": "Automatisch nach Lautstärke",
      "Chaos": "Chaos",
      "Pile": "Stapel",
      "Grid": "Raster",
      "Mosaic": "Mosaik",
      "Spotlight": "Spotlight",
      "Spiral": "Spirale",
      "Scattered everywhere. Drag to move, mouse wheel to scale.": "Überall verstreut. Ziehen zum Verschieben, Mausrad zum Skalieren.",
      "Like photos on a table, heaped towards the middle.": "Wie Fotos auf einem Tisch, zur Mitte hin aufgehäuft.",
      "Fixed cells that fill the whole screen.": "Feste Zellen, die den ganzen Bildschirm füllen.",
      "Pinboard columns: new items come in at the top, the rest slides down.": "Pinnwand-Spalten: Neue Elemente kommen oben herein, der Rest rutscht nach unten.",
      "The newest item big in the middle, the older ones in a circle around it.": "Das neueste Element groß in der Mitte, die älteren im Kreis darum.",
      "Sunflower spiral with the newest item in the middle – every wave turns everything further.": "Sonnenblumen-Spirale mit dem neuesten Element in der Mitte – jede Welle dreht alles weiter.",
      "Lanes from right to left. Items that have passed make room for new ones.": "Bahnen von rechts nach links. Vorbeigezogene Elemente machen Platz für neue.",
      "Falls through from the top. At the bottom, items make room for new ones.": "Fällt von oben herab. Unten machen Elemente Platz für neue.",
      "Avoid overlap – free spots first": "Überlappung vermeiden – freie Plätze zuerst",
      "Size min": "Größe min.",
      "Size max": "Größe max.",
      "Rotation": "Drehung",
      "Spacing": "Abstand",
      "Columns": "Spalten",
      "Speed": "Geschwindigkeit",
      "Frame": "Rahmen",
      "Soft": "Weich",
      "None": "Keiner",
      "Polaroid": "Polaroid",
      "Circle": "Kreis",
      "Square": "Quadrat",
      "Shape": "Form",
      "Format": "Format",
      "Landscape 16:9": "Querformat 16:9",
      "Portrait 3:4": "Hochformat 3:4",
      "Appear": "Erscheinen",
      "Zoom": "Zoom",
      "Fade in": "Einblenden",
      "Fade in and out": "Ein- und ausblenden",
      "Slam": "Slam",
      "Flip": "Flip",
      "Fall": "Fallen",
      "Spin": "Drehen",
      "Glitch start": "Glitch-Start",
      "Motion": "Bewegung",
      "Drift": "Driften",
      "Breathe": "Atmen",
      "Wobble": "Wackeln",
      "Hold still": "Stillhalten",
      "Pulse": "Puls",
      "Color rush": "Farbrausch",
      "Glitch": "Glitch",
      "Blending": "Überblendung",
      "Normal": "Normal",
      "Double exposure": "Doppelbelichtung",
      "Negative": "Negativ",
      "Negative rush": "Negativ-Rausch",
      "Texture": "Textur",
      "Film grain": "Filmkorn",
      "Halftone": "Halbton",
      "Vignette": "Vignette",
      "3D depth – parallax with the mouse": "3D-Tiefe – Parallaxe mit der Maus",
      "Reflection": "Spiegelung",
      "Reflection under every item": "Spiegelung unter jedem Element",
      "Shake": "Wackeln",
      "Flash": "Blitz",
      "The flash is gentle and comes at most once per wave.": "Der Blitz ist sanft und kommt höchstens einmal pro Welle.",
      "Just zoom and fade": "Nur Zoom und Überblenden",
      "Darken": "Abdunkeln",
      "Blur": "Weichzeichnen",
      "soft": "weich",
      "rerolls itself": "würfelt sich selbst neu",
      "New background": "Neuer Hintergrund",
      "Reroll automatically": "Automatisch neu würfeln",
      "On every new wave": "Bei jeder neuen Welle",
      "Artwork in the design": "Artwork im Design",
      "Show images in the panel and at the start": "Bilder im Panel und beim Start zeigen",
      "e.g. Artwork": "z. B. Artwork",
      "Uses images and scene screenshots with this tag and from folders with the same name. Click the cover for the next image.": "Nutzt Bilder und Szenen-Screenshots mit diesem Tag sowie aus Ordnern mit gleichem Namen. Klicke aufs Cover für das nächste Bild.",
      "Next image": "Nächstes Bild",
      "No background images found (tag “background”)": "Keine Hintergrundbilder gefunden (Tag „background“)",
      "The Random Backgrounds plugin is not active": "Das Plugin Random Backgrounds ist nicht aktiv",
      "plugin not active": "Plugin nicht aktiv",
      "Source": "Quelle",
      "Whole library": "Ganze Bibliothek",
      "Current page": "Aktuelle Seite",
      "Current page (performer/tag/…)": "Aktuelle Seite (Darsteller/Tag/…)",
      "“Current page” uses the performer, tag, studio, gallery or group page you start from. On tag pages, your own tags always all have to match.": "„Aktuelle Seite“ nutzt die Darsteller-, Tag-, Studio-, Galerie- oder Gruppenseite, von der du startest. Auf Tag-Seiten müssen deine eigenen Tags immer alle passen.",
      "Not a performer/tag/studio/gallery/group page – using the whole library": "Keine Darsteller-/Tag-/Studio-/Galerie-/Gruppenseite – es wird die ganze Bibliothek verwendet",
      "Only with tags": "Nur mit Tags",
      "Exclude tags": "Tags ausschließen",
      "Marker clips": "Marker-Clips",
      "Marker clips are the short moments you marked in your scenes. This share of the videos plays them (only the marked part, looping) instead of whole scenes. Choose which markers under Source & filters.": "Marker-Clips sind die kurzen Momente, die du in deinen Szenen markiert hast. Dieser Anteil der Videos spielt sie (nur den markierten Teil, in Schleife) statt ganzer Szenen. Welche Marker, wählst du unter Quelle & Filter.",
      "Only marker clips with tags": "Nur Marker-Clips mit Tags",
      "Needs a share of marker clips under Media. Primary or extra tag of the marker; the filters above apply to the marker's scene.": "Braucht einen Anteil an Marker-Clips unter Medien. Haupt- oder Zusatz-Tag des Markers; die Filter oben gelten für die Szene des Markers.",
      "All tags must match": "Alle Tags müssen passen",
      "Including sub-tags (recursive)": "Untertags einbeziehen (rekursiv)",
      "Tags apply to": "Tags gelten für",
      "Scenes and images": "Szenen und Bilder",
      "Only with tags (marker clips)": "Nur mit Tags (Marker-Clips)",
      "The tag box edits the kind chosen above; the other kind keeps its own tags. Marker clips need a share under Media – their tags are the marker's primary or extra tag, and the filters apply to the marker's scene too. Exclude tags and the two switches count for all kinds.": "Das Tag-Feld bearbeitet die oben gewählte Art; die andere Art behält ihre eigenen Tags. Marker-Clips brauchen einen Anteil unter Medien – ihre Tags sind das Haupt- oder Zusatz-Tag des Markers, und die Filter gelten auch für die Szene des Markers. Ausgeschlossene Tags und die beiden Schalter gelten für alle Arten.",
      "On tag pages, all chosen tags must match": "Auf Tag-Seiten müssen alle gewählten Tags passen",
      "Minimum rating": "Mindestbewertung",
      "Only with favorite performers": "Nur mit Lieblingsdarstellern",
      "favorites": "Favoriten",
      "Search tag…": "Tag suchen…",
      "No tags found": "Keine Tags gefunden",
      "A playlist (from Stash UI)": "Eine Playlist (aus Stash UI)",
      "Playlist": "Playlist",
      "A playlist": "Eine Playlist",
      "No playlists yet": "Noch keine Playlists",
      "Stash UI's smart playlists: set filters in Scenes or Images there and press “Save as playlist”. The playlist decides – the filters below don't apply.": "Die Smart-Playlists von Stash UI: Stelle dort in Szenen oder Bildern Filter ein und drücke „Als Playlist speichern“. Die Playlist entscheidet – die Filter unten gelten nicht.",
      "Only with performers": "Nur mit Darstellern",
      "All performers must be in it": "Alle Darsteller müssen vorkommen",
      "Search performer…": "Darsteller suchen…",
      "No performers found": "Keine Darsteller gefunden",
      "Resolution up to": "Auflösung bis",
      "Videos at least": "Videos mindestens",
      "any length": "beliebige Länge",
      "1 min": "1 Min.",
      "5 min": "5 Min.",
      "20 min": "20 Min.",
      "A lower resolution runs smoother – 4K videos take the most.": "Eine niedrigere Auflösung läuft flüssiger – 4K-Videos brauchen am meisten.",
      "All folders": "Alle Ordner",
      "Filter folders…": "Ordner filtern…",
      "Loading folders…": "Ordner werden geladen…",
      "No folders found": "Keine Ordner gefunden",
      "Without a choice, the whole library is used. Subfolders are always included. Numbers: images (I) and videos (V).": "Ohne Auswahl wird die ganze Bibliothek verwendet. Unterordner sind immer eingeschlossen. Zahlen: Bilder (I) und Videos (V).",
      "RedGifs share": "RedGifs-Anteil",
      "Niches, tags & creators": "Nischen, Tags & Creator",
      "Search niches, tags, creators …": "Nischen, Tags, Creator suchen …",
      "Niche": "Nische",
      "Niches": "Nischen",
      "Tag": "Tag",
      "Tags": "Tags",
      "Creator": "Creator",
      "Verified": "Verifiziert",
      "Trending": "Trends",
      "Top of the week": "Top der Woche",
      "Top of the month": "Top des Monats",
      "Top (all time)": "Top (aller Zeiten)",
      "Latest": "Neueste",
      "Sort order": "Sortierung",
      "Quality": "Qualität",
      "Saving (⬇ on hover or key D)": "Speichern (⬇ beim Überfahren oder Taste D)",
      "Save location": "Speicherort",
      "Everything in one folder": "Alles in einem Ordner",
      "By source (niche/tag/creator)": "Nach Quelle (Nische/Tag/Creator)",
      "By the clip's creator": "Nach Creator des Clips",
      "Always saved in HD. If the save location is inside your Stash library, Stash scans the folder right away and the scene gets the link, title and the tag “RedGifs”.": "Wird immer in HD gespeichert. Liegt der Speicherort in deiner Stash-Bibliothek, scannt Stash den Ordner sofort, und die Szene bekommt Link, Titel und den Tag „RedGifs“.",
      "Save the RedGifs clip under the mouse to Stash": "Den RedGifs-Clip unter der Maus in Stash speichern",
      "Hover over a RedGifs clip, then press D": "Über einen RedGifs-Clip fahren, dann D drücken",
      "Save to Stash (D)": "In Stash speichern (D)",
      "Open in Stash or on RedGifs": "In Stash oder auf RedGifs öffnen",
      "Open in Stash (Ctrl+click)": "In Stash öffnen (Strg+Klick)",
      "Open on RedGifs (Ctrl+click)": "Auf RedGifs öffnen (Strg+Klick)",
      "Already saved": "Schon gespeichert",
      "Already there": "Schon vorhanden",
      "Saved": "Gespeichert",
      "Saved – Stash is still scanning, the scene will appear shortly": "Gespeichert – Stash scannt noch, die Szene erscheint gleich",
      "Saved, but importing into Stash failed:": "Gespeichert, aber der Import in Stash ist fehlgeschlagen:",
      "Download failed:": "Download fehlgeschlagen:",
      "Failed – try again": "Fehlgeschlagen – versuche es erneut",
      "Authentication failed": "Authentifizierung fehlgeschlagen",
      "creator not found": "Creator nicht gefunden",
      "not found": "nicht gefunden",
      "no Stash library configured": "keine Stash-Bibliothek konfiguriert",
      "no answer from the plugin backend": "keine Antwort vom Plugin-Backend",
      "Preset": "Preset",
      "Name for a new preset": "Name für ein neues Preset",
      "A preset of your own saves all settings, including source, filters and RedGifs.": "Ein eigenes Preset speichert alle Einstellungen, auch Quelle, Filter und RedGifs.",
      "Save": "Speichern",
      "Load": "Laden",
      "Delete": "Löschen",
      "None yet": "Noch keine",
      "Reset everything to defaults": "Alles auf Standard zurücksetzen",
      "Settings reset": "Einstellungen zurückgesetzt",
      "Sleep timer": "Einschlaf-Timer",
      "Sleep timer ran out – good night": "Der Einschlaf-Timer ist abgelaufen – gute Nacht",
      "The sleep timer stops with a fade-out and closes the storm tab.": "Der Einschlaf-Timer stoppt mit Ausblenden und schließt den Storm-Tab.",
      "Afterwards": "Danach",
      "This panel": "Dieses Panel",
      "Show the HUD in the storm tab": "HUD im Storm-Tab anzeigen",
      "Show item big": "Element groß anzeigen",
      "Remove item": "Element entfernen",
      "Remove (right-click)": "Entfernen (Rechtsklick)",
      "Remove all items": "Alle Elemente entfernen",
      "Stop everything (with fade-out)": "Alles stoppen (mit Ausblenden)",
      "Change layout": "Layout ändern",
      "Move item (chaos, pile)": "Element verschieben (Chaos, Stapel)",
      "Scale item (chaos, pile)": "Element skalieren (Chaos, Stapel)",
      "Click": "Klick",
      "Ctrl+click": "Strg+Klick",
      "Right-click": "Rechtsklick",
      "Drag": "Ziehen",
      "Mouse wheel": "Mausrad",
      "Space": "Leertaste",
      "Volume ±5": "Lautstärke ±5",
      "Remove": "Entfernen",
      "Unknown": "Unbekannt",
      "Off": "Aus",
      "off": "aus",
      "auto": "auto",
      "Max": "Max",
      "Mixed": "Gemischt",
      "Random": "Zufällig",
      "Performer": "Darsteller",
      "Studio": "Studio",
      "Group": "Gruppe",
      "Scene": "Szene",
      "Image": "Bild",
      "Tag or folder": "Tag oder Ordner",
      "preview clips": "Vorschau-Clips",
      "endless": "endlos",
      "The storm tab detects tempo and beats itself (a few seconds per song), and the song loops. New items load ahead and appear exactly on the beat. Automatic: calm parts every bar, medium every 2 beats, loud every beat – drops right away. With pulse, the stage pumps on every beat; flash and shake come with the waves. “New wave every” doesn't apply then.": "Der Storm-Tab erkennt Tempo und Beats selbst (ein paar Sekunden pro Song), und der Song läuft in Schleife. Neue Elemente laden voraus und erscheinen genau im Beat. Automatisch: ruhige Teile jeden Takt, mittlere alle 2 Beats, laute jeden Beat – Drops sofort. Mit Puls pumpt die Bühne bei jedem Beat; Blitz und Wackeln kommen mit den Wellen. „Neue Welle alle“ gilt dann nicht.",
      "Loop videos (off = fade out after the end)": "Videos in Schleife (aus = nach dem Ende ausblenden)",
      "Rush": "Rausch",
      "any": "beliebig",
      "SD (faster)": "SD (schneller)",
      "HD (sharper)": "HD (schärfer)",
      "Typing shows matching niches, tags and creators live – click (or ↑/↓ + Enter) to add them. Several are possible; one of them is picked at random per fetch. Without a choice you get trending. RedGifs only plays in the storm tab.": "Beim Tippen erscheinen passende Nischen, Tags und Creator live – klicke (oder ↑/↓ + Enter), um sie hinzuzufügen. Mehrere sind möglich; bei jedem Abruf wird einer zufällig gewählt. Ohne Auswahl bekommst du Trends. RedGifs spielt nur im Storm-Tab.",
      "HUD on/off": "HUD an/aus",
      "Full videos at once": "Ganze Videos gleichzeitig",
      "0 = automatic: Media Storm measures how quickly Stash still answers and plays as many full videos as the connection allows. Over plain HTTP, browsers keep only about 6 connections to one server – when they're all taken, Stash stops answering in this browser. Further videos play as preview clips (or show their cover).": "0 = automatisch: Media Storm misst, wie schnell Stash noch antwortet, und spielt so viele ganze Videos ab, wie die Verbindung zulässt. Über einfaches HTTP halten Browser nur etwa 6 Verbindungen zu einem Server – sind alle belegt, antwortet Stash in diesem Browser nicht mehr. Weitere Videos laufen als Vorschau-Clips (oder zeigen ihr Cover).",
    },
    patterns: [
      ["Playlist “(.+)”", "Playlist „$1“"],
      ["(.+) \\((scenes|images)\\)", "$1 ($2)"],
      ["up to (\\d+)p", "bis $1p"],
      ["≥ (\\d+) min", "≥ $1 Min."],
      ["(\\d+) performers", "$1 Darsteller"],
      ["On the beat (\\d+) new, max (\\d+) endless", "Im Beat · $1 neue, max. $2 · endlos"],
      ["On the beat (\\d+) new, max (\\d+)", "Im Beat · $1 neue, max. $2"],
      ["Every (\\d+) s (\\d+) new, max (\\d+) endless", "Alle $1 Sek. · $2 neue, max. $3 · endlos"],
      ["Every (\\d+) s (\\d+) new, max (\\d+)", "Alle $1 Sek. · $2 neue, max. $3"],
      ["(\\d+) % marker clips", "$1 % Marker-Clips"],
      ["Also active: (\\d+) tags? for scenes and images", "Zusätzlich aktiv: $1 Tag(s) für Szenen und Bilder"],
      ["Also active: (\\d+) tags? for marker clips", "Zusätzlich aktiv: $1 Tag(s) für Marker-Clips"],
      ["(\\d+) marker tags? \\+sub", "$1 Marker-Tags (mit Untertags)"],
      ["(\\d+) marker tags?", "$1 Marker-Tags"],
      ["(\\d+) % of the videos", "$1 % der Videos"],
      ["(\\d+) % videos, preview clips", "$1 % Videos, Vorschau-Clips"],
      ["(\\d+) % videos", "$1 % Videos"],
      ["(\\d+) % images, (\\d+) % videos", "$1 % Bilder, $2 % Videos"],
      ["(\\d+) %, (.+)", "$1 %, $2"],
      ["(.+?), frame (.+)", "$1, Rahmen $2"],
      ["Darkened (\\d+) %(.*)", "Abgedunkelt $1 %$2"],
      ["(\\d+) tags?", "$1 Tags"],
      ["without (\\d+)", "ohne $1"],
      ["from (★+)", "ab $1"],
      ["(\\d+) saved", "$1 gespeichert"],
      ["(\\d+) s", "$1 Sek."],
      ["(\\d+) min", "$1 Min."],
      ["level (\\d+)", "Stufe $1"],
      ["every (\\d+) waves", "alle $1 Wellen"],
      ["(\\d+) % of items", "$1 % der Elemente"],
      ["(\\d+) px/s", "$1 px/s"],
      ["Volume (\\d+) ?%", "Lautstärke $1 %"],
      ["· (\\d+) Clips", "· $1 Clips"],
      ["Mood “(.+)”", "Stimmung „$1“"],
      ["Preset “(.+)” deleted", "Preset „$1“ gelöscht"],
      ["Preset “(.+)” loaded", "Preset „$1“ geladen"],
      ["Preset “(.+)” saved", "Preset „$1“ gespeichert"],
      ["Song “(.+)” chosen", "Song „$1“ gewählt"],
      ["On the beat: (.+) BPM", "Im Beat: $1 BPM"],
      ["On the beat: detecting beats in “(.+)” …", "Im Beat: Beats in „$1“ werden erkannt …"],
      ["Imported into Stash ✓ \\((.+?) #(\\d+)\\)", "In Stash importiert ✓ ($1 #$2)"],
      ["Error while loading: (.+)", "Fehler beim Laden: $1"],
      ["Background error: (.+)", "Hintergrundfehler: $1"],
      ["Error: (.+)", "Fehler: $1"],
      ["Download failed: (.+)", "Download fehlgeschlagen: $1"],
      ["Saved, but importing into Stash failed: (.+)", "Gespeichert, aber der Import in Stash ist fehlgeschlagen: $1"],
      ["GraphQL error: (.+)", "GraphQL-Fehler: $1"],
      ["Media Storm (\\d[\\d.]*)", "Media Storm $1"],
      ["([\\d.,]+) Tsd\\.", "$1 Tsd."],
      ["([\\d.,]+) Mio\\.", "$1 Mio."],
    ],
  };
})();
