// Media Storm in Spanish. Loaded before mediaStorm.js; the English text as shown is the key.
// Patterns catch texts with numbers or names ($1, $2 … = the parts in brackets, translated too if they
// are in `texts`). The language follows Stash UI's choice, otherwise Stash's interface language.
(function () {
  window.MediaStormLocales = window.MediaStormLocales || {};
  window.MediaStormLocales["es"] = {
    sep: ", ",
    texts: {
      "Media Storm": "Media Storm",
      "Storm": "Storm",
      "Ready": "Listo",
      "Running": "En ejecución",
      "Paused": "En pausa",
      "Stopped": "Detenido",
      "starts in its own tab": "se inicia en su propia pestaña",
      "Running in the storm tab": "En ejecución en la pestaña storm",
      "Start": "Iniciar",
      "Stop": "Detener",
      "Restart": "Reiniciar",
      "Pause": "Pausa",
      "Pause / resume": "Pausa / reanudar",
      "Pause / resume (Space)": "Pausa / reanudar (Espacio)",
      "Next wave": "Siguiente oleada",
      "Next wave now (N)": "Siguiente oleada ahora (N)",
      "Next wave right away": "Siguiente oleada de inmediato",
      "New wave": "Nueva oleada",
      "Reroll background": "Cambiar el fondo al azar",
      "Reroll background (B)": "Cambiar el fondo al azar (B)",
      "Close (Esc)": "Cerrar (Esc)",
      "Close panel": "Cerrar el panel",
      "Stop (Esc)": "Detener (Esc)",
      "Settings (S)": "Ajustes (S)",
      "Settings": "Ajustes",
      "Fullscreen (F)": "Pantalla completa (F)",
      "Fullscreen": "Pantalla completa",
      "Fullscreen not allowed": "Pantalla completa no permitida",
      "Liquid glass": "Cristal líquido",
      "Back": "Volver",
      "Back to the overview (Esc)": "Volver al resumen (Esc)",
      "Hotkeys & mouse": "Atajos y ratón",
      "Expand/collapse": "Expandir/contraer",
      "Click or press a key for sound": "Haz clic o pulsa una tecla para activar el sonido",
      "A freshly opened storm tab may only play sound after a click or key press.": "Una pestaña storm recién abierta puede que solo reproduzca sonido tras un clic o una tecla.",
      "Nothing found": "No se encontró nada",
      "With these filters there are no images or videos. Loosen tags, folders or rating – or reset everything.": "Con estos filtros no hay imágenes ni vídeos. Relaja etiquetas, carpetas o valoración, o restablece todo.",
      "Reset filters": "Restablecer filtros",
      "Filters reset – whole library": "Filtros restablecidos: toda la biblioteca",
      "No media found for this source/filter": "No se encontraron medios para esta fuente/filtro",
      "First wave loading …": "Cargando la primera oleada …",
      "Searching …": "Buscando …",
      "Error while loading:": "Error al cargar:",
      "Background error:": "Error de fondo:",
      "GraphQL error:": "Error de GraphQL:",
      "Pop-up blocked – please allow pop-ups for Stash": "Ventana emergente bloqueada: permite las ventanas emergentes para Stash",
      "Mood": "Ambiente",
      "Next mood": "Siguiente ambiente",
      "Default": "Predeterminado",
      "Chaos as usual": "Caos de siempre",
      "Chill": "Chill",
      "Pile, calm, breathing": "Montón, calma, respirando",
      "Fast, full, shaking": "Rápido, lleno, temblando",
      "Gallery": "Galería",
      "Mosaic, tidy": "Mosaico, ordenado",
      "Cinema": "Cine",
      "Spotlight, videos only": "Foco, solo vídeos",
      "Trip": "Viaje",
      "Spiral, colors, 3D": "Espiral, colores, 3D",
      "Ticker": "Ticker",
      "Polaroids drift by": "Polaroids que pasan flotando",
      "Rain": "Lluvia",
      "Falls through from the top": "Cae desde arriba",
      "Manga": "Manga",
      "Ink, halftone, impact": "Tinta, trama, impacto",
      "Neon": "Neón",
      "Glow, glitch, beat": "Brillo, glitch, ritmo",
      "Tempo": "Tempo",
      "On the beat": "Al ritmo",
      "Media": "Medios",
      "Sound": "Sonido",
      "Layout": "Disposición",
      "Layout:": "Disposición:",
      "Effects": "Efectos",
      "Background": "Fondo",
      "Source & filters": "Fuente y filtros",
      "Folders": "Carpetas",
      "RedGifs": "RedGifs",
      "My presets": "Mis preajustes",
      "New wave every": "Nueva oleada cada",
      "Every": "Cada",
      "Items per wave": "Elementos por oleada",
      "First wave (right away)": "Primera oleada (de inmediato)",
      "At most at once": "Máximo a la vez",
      "Items / Maximum": "Elementos / Máximo",
      "Endless – replace the oldest items instead of stopping": "Sin fin: reemplaza los elementos más antiguos en lugar de detenerse",
      "Waves on the beat of a song": "Oleadas al ritmo de una canción",
      "Choose song …": "Elegir canción …",
      "No song yet": "Aún no hay canción",
      "No song chosen": "Ninguna canción elegida",
      "Song volume": "Volumen de la canción",
      "Every 2 beats": "Cada 2 pulsos",
      "Every bar (4 beats)": "Cada compás (4 pulsos)",
      "Every 2 bars": "Cada 2 compases",
      "On every beat": "En cada pulso",
      "Couldn't save the song (storage blocked?)": "No se pudo guardar la canción (¿almacenamiento bloqueado?)",
      "On the beat: click or press a key to start the music": "Al ritmo: haz clic o pulsa una tecla para iniciar la música",
      "On the beat: couldn't read the song": "Al ritmo: no se pudo leer la canción",
      "On the beat: no song chosen yet (panel → On the beat) – waves run by time": "Al ritmo: aún no hay canción elegida (panel → Al ritmo); las oleadas van por tiempo",
      "Images": "Imágenes",
      "Videos": "Vídeos",
      "Mix": "Mezcla",
      "Video source": "Fuente de vídeo",
      "Full video": "Vídeo completo",
      "Preview clip (lighter)": "Clip de vista previa (más ligero)",
      "Image quality": "Calidad de imagen",
      "Thumbnail (faster)": "Miniatura (más rápido)",
      "Original": "Original",
      "Random start": "Inicio aleatorio",
      "Random start point in the video": "Punto de inicio aleatorio en el vídeo",
      "Ken Burns zoom on images": "Zoom Ken Burns en las imágenes",
      "Volume": "Volumen",
      "Audible": "Audible",
      "all videos": "todos los vídeos",
      "All videos": "Todos los vídeos",
      "under the mouse": "bajo el ratón",
      "Only under the mouse": "Solo bajo el ratón",
      "newest video": "vídeo más reciente",
      "Only the newest video": "Solo el vídeo más reciente",
      "muted": "silenciado",
      "Muted": "Silenciado",
      "Automatic by loudness": "Automático según el volumen",
      "Chaos": "Caos",
      "Pile": "Montón",
      "Grid": "Cuadrícula",
      "Mosaic": "Mosaico",
      "Spotlight": "Foco",
      "Spiral": "Espiral",
      "Scattered everywhere. Drag to move, mouse wheel to scale.": "Esparcido por todas partes. Arrastra para mover, rueda del ratón para escalar.",
      "Like photos on a table, heaped towards the middle.": "Como fotos sobre una mesa, amontonadas hacia el centro.",
      "Fixed cells that fill the whole screen.": "Celdas fijas que llenan toda la pantalla.",
      "Pinboard columns: new items come in at the top, the rest slides down.": "Columnas de corcho: los elementos nuevos entran arriba y el resto se desliza hacia abajo.",
      "The newest item big in the middle, the older ones in a circle around it.": "El elemento más reciente grande en el centro y los más antiguos en círculo a su alrededor.",
      "Sunflower spiral with the newest item in the middle – every wave turns everything further.": "Espiral de girasol con el elemento más reciente en el centro; cada oleada gira todo un poco más.",
      "Lanes from right to left. Items that have passed make room for new ones.": "Carriles de derecha a izquierda. Los elementos que han pasado dejan sitio a los nuevos.",
      "Falls through from the top. At the bottom, items make room for new ones.": "Cae desde arriba. Abajo, los elementos dejan sitio a los nuevos.",
      "Avoid overlap – free spots first": "Evitar solapamientos: primero los huecos libres",
      "Size min": "Tamaño mín.",
      "Size max": "Tamaño máx.",
      "Rotation": "Rotación",
      "Spacing": "Espaciado",
      "Columns": "Columnas",
      "Speed": "Velocidad",
      "Frame": "Marco",
      "Soft": "Suave",
      "None": "Ninguno",
      "Polaroid": "Polaroid",
      "Circle": "Círculo",
      "Square": "Cuadrado",
      "Shape": "Forma",
      "Format": "Formato",
      "Landscape 16:9": "Horizontal 16:9",
      "Portrait 3:4": "Vertical 3:4",
      "Appear": "Aparición",
      "Zoom": "Zoom",
      "Fade in": "Aparecer en fundido",
      "Fade in and out": "Fundido de entrada y salida",
      "Slam": "Golpe",
      "Flip": "Volteo",
      "Fall": "Caída",
      "Spin": "Giro",
      "Glitch start": "Inicio con glitch",
      "Motion": "Movimiento",
      "Drift": "Deriva",
      "Breathe": "Respiración",
      "Wobble": "Bamboleo",
      "Hold still": "Quieto",
      "Pulse": "Pulso",
      "Color rush": "Oleada de color",
      "Glitch": "Glitch",
      "Blending": "Fusión",
      "Normal": "Normal",
      "Double exposure": "Doble exposición",
      "Negative": "Negativo",
      "Negative rush": "Oleada de negativo",
      "Texture": "Textura",
      "Film grain": "Grano de película",
      "Halftone": "Trama",
      "Vignette": "Viñeta",
      "3D depth – parallax with the mouse": "Profundidad 3D: paralaje con el ratón",
      "Reflection": "Reflejo",
      "Reflection under every item": "Reflejo bajo cada elemento",
      "Shake": "Sacudida",
      "Flash": "Destello",
      "The flash is gentle and comes at most once per wave.": "El destello es suave y llega como mucho una vez por oleada.",
      "Just zoom and fade": "Solo zoom y fundido",
      "Darken": "Oscurecer",
      "Blur": "Desenfoque",
      "soft": "suave",
      "rerolls itself": "se cambia solo",
      "New background": "Nuevo fondo",
      "Reroll automatically": "Cambiar automáticamente",
      "On every new wave": "En cada nueva oleada",
      "Artwork in the design": "Ilustraciones en el diseño",
      "Show images in the panel and at the start": "Mostrar imágenes en el panel y al inicio",
      "e.g. Artwork": "p. ej. Artwork",
      "Uses images and scene screenshots with this tag and from folders with the same name. Click the cover for the next image.": "Usa imágenes y capturas de escenas con esta etiqueta y de carpetas con el mismo nombre. Haz clic en la portada para ver la siguiente imagen.",
      "Next image": "Siguiente imagen",
      "No background images found (tag “background”)": "No se encontraron imágenes de fondo (etiqueta «background»)",
      "The Random Backgrounds plugin is not active": "El plugin Random Backgrounds no está activo",
      "plugin not active": "plugin no activo",
      "Source": "Fuente",
      "Whole library": "Toda la biblioteca",
      "Current page": "Página actual",
      "Current page (performer/tag/…)": "Página actual (artista/etiqueta/…)",
      "“Current page” uses the performer, tag, studio, gallery or group page you start from. On tag pages, your own tags always all have to match.": "«Página actual» usa la página de artista, etiqueta, estudio, galería o grupo desde la que empiezas. En las páginas de etiqueta, todas tus propias etiquetas tienen que coincidir.",
      "Not a performer/tag/studio/gallery/group page – using the whole library": "No es una página de artista/etiqueta/estudio/galería/grupo: se usa toda la biblioteca",
      "Only with tags": "Solo con las etiquetas",
      "Exclude tags": "Excluir etiquetas",
      "Marker clips": "Clips de marcadores",
      "Marker clips are the short moments you marked in your scenes. This share of the videos plays them (only the marked part, looping) instead of whole scenes. Choose which markers under Source & filters.": "Los clips de marcadores son los momentos cortos que marcaste en tus escenas. Esta proporción de los vídeos los reproduce (solo la parte marcada, en bucle) en lugar de escenas enteras. Elige qué marcadores en Fuente y filtros.",
      "Only marker clips with tags": "Solo clips de marcadores con etiquetas",
      "Needs a share of marker clips under Media. Primary or extra tag of the marker; the filters above apply to the marker's scene.": "Necesita una proporción de clips de marcadores en Medios. Etiqueta principal o adicional del marcador; los filtros de arriba se aplican a la escena del marcador.",
      "All tags must match": "Todas las etiquetas tienen que coincidir",
      "Including sub-tags (recursive)": "Incluir subetiquetas (recursivo)",
      "Tags apply to": "Las etiquetas se aplican a",
      "Scenes and images": "Escenas e imágenes",
      "Only with tags (marker clips)": "Solo con las etiquetas (clips de marcadores)",
      "The tag box edits the kind chosen above; the other kind keeps its own tags. Marker clips need a share under Media – their tags are the marker's primary or extra tag, and the filters apply to the marker's scene too. Exclude tags and the two switches count for all kinds.": "El campo de etiquetas edita el tipo elegido arriba; el otro tipo conserva sus propias etiquetas. Los clips de marcadores necesitan una proporción en Medios – sus etiquetas son la etiqueta principal o extra del marcador, y los filtros se aplican también a la escena del marcador. Las etiquetas excluidas y los dos interruptores valen para todos los tipos.",
      "On tag pages, all chosen tags must match": "En las páginas de etiqueta, todas las etiquetas elegidas tienen que coincidir",
      "Minimum rating": "Valoración mínima",
      "Only with favorite performers": "Solo con artistas favoritos",
      "favorites": "favoritos",
      "Search tag…": "Buscar etiqueta…",
      "No tags found": "No se encontraron etiquetas",
      "A playlist (from Stash UI)": "Una lista (de Stash UI)",
      "Playlist": "Lista de reproducción",
      "A playlist": "Una lista",
      "No playlists yet": "Aún no hay listas",
      "Stash UI's smart playlists: set filters in Scenes or Images there and press “Save as playlist”. The playlist decides – the filters below don't apply.": "Las listas inteligentes de Stash UI: define filtros en Escenas o Imágenes allí y pulsa «Guardar como lista». La lista manda; los filtros de abajo no se aplican.",
      "Only with performers": "Solo con los artistas",
      "All performers must be in it": "Todos los artistas tienen que estar",
      "Search performer…": "Buscar artista…",
      "No performers found": "No se encontraron artistas",
      "Resolution up to": "Resolución hasta",
      "Videos at least": "Vídeos de al menos",
      "any length": "cualquier duración",
      "1 min": "1 min",
      "5 min": "5 min",
      "20 min": "20 min",
      "A lower resolution runs smoother – 4K videos take the most.": "Una resolución menor va más fluida; los vídeos 4K son lo más pesado.",
      "All folders": "Todas las carpetas",
      "Filter folders…": "Filtrar carpetas…",
      "Loading folders…": "Cargando carpetas…",
      "No folders found": "No se encontraron carpetas",
      "Without a choice, the whole library is used. Subfolders are always included. Numbers: images (I) and videos (V).": "Sin elección se usa toda la biblioteca. Las subcarpetas siempre se incluyen. Números: imágenes (I) y vídeos (V).",
      "RedGifs share": "Proporción de RedGifs",
      "Niches, tags & creators": "Nichos, etiquetas y creadores",
      "Search niches, tags, creators …": "Buscar nichos, etiquetas, creadores …",
      "Niche": "Nicho",
      "Niches": "Nichos",
      "Tag": "Etiqueta",
      "Tags": "Etiquetas",
      "Creator": "Creador",
      "Verified": "Verificado",
      "Trending": "Tendencias",
      "Top of the week": "Lo mejor de la semana",
      "Top of the month": "Lo mejor del mes",
      "Top (all time)": "Lo mejor (de siempre)",
      "Latest": "Lo último",
      "Sort order": "Orden",
      "Quality": "Calidad",
      "Saving (⬇ on hover or key D)": "Guardado (⬇ al pasar el ratón o tecla D)",
      "Save location": "Ubicación de guardado",
      "Everything in one folder": "Todo en una sola carpeta",
      "By source (niche/tag/creator)": "Por fuente (nicho/etiqueta/creador)",
      "By the clip's creator": "Por creador del clip",
      "Always saved in HD. If the save location is inside your Stash library, Stash scans the folder right away and the scene gets the link, title and the tag “RedGifs”.": "Siempre se guarda en HD. Si la ubicación está dentro de tu biblioteca de Stash, Stash escanea la carpeta enseguida y la escena recibe el enlace, el título y la etiqueta «RedGifs».",
      "Save the RedGifs clip under the mouse to Stash": "Guardar en Stash el clip de RedGifs bajo el ratón",
      "Hover over a RedGifs clip, then press D": "Pasa el ratón sobre un clip de RedGifs y pulsa D",
      "Save to Stash (D)": "Guardar en Stash (D)",
      "Open in Stash or on RedGifs": "Abrir en Stash o en RedGifs",
      "Open in Stash (Ctrl+click)": "Abrir en Stash (Ctrl+clic)",
      "Open on RedGifs (Ctrl+click)": "Abrir en RedGifs (Ctrl+clic)",
      "Already saved": "Ya guardado",
      "Already there": "Ya está",
      "Saved": "Guardado",
      "Saved – Stash is still scanning, the scene will appear shortly": "Guardado: Stash aún está escaneando; la escena aparecerá enseguida",
      "Saved, but importing into Stash failed:": "Guardado, pero falló la importación a Stash:",
      "Download failed:": "Falló la descarga:",
      "Failed – try again": "Falló: inténtalo de nuevo",
      "Authentication failed": "Falló la autenticación",
      "creator not found": "creador no encontrado",
      "not found": "no encontrado",
      "no Stash library configured": "no hay ninguna biblioteca de Stash configurada",
      "no answer from the plugin backend": "sin respuesta del backend del plugin",
      "Preset": "Preajuste",
      "Name for a new preset": "Nombre del nuevo preajuste",
      "A preset of your own saves all settings, including source, filters and RedGifs.": "Un preajuste propio guarda todos los ajustes, incluidos fuente, filtros y RedGifs.",
      "Save": "Guardar",
      "Load": "Cargar",
      "Delete": "Eliminar",
      "None yet": "Ninguno todavía",
      "Reset everything to defaults": "Restablecer todo a los valores predeterminados",
      "Settings reset": "Ajustes restablecidos",
      "Sleep timer": "Temporizador de apagado",
      "Sleep timer ran out – good night": "El temporizador se agotó: buenas noches",
      "The sleep timer stops with a fade-out and closes the storm tab.": "El temporizador se detiene con un fundido de salida y cierra la pestaña storm.",
      "Afterwards": "Después",
      "This panel": "Este panel",
      "Show the HUD in the storm tab": "Mostrar el HUD en la pestaña storm",
      "Show item big": "Mostrar el elemento en grande",
      "Remove item": "Quitar elemento",
      "Remove (right-click)": "Quitar (clic derecho)",
      "Remove all items": "Quitar todos los elementos",
      "Stop everything (with fade-out)": "Detener todo (con fundido)",
      "Change layout": "Cambiar disposición",
      "Move item (chaos, pile)": "Mover elemento (caos, montón)",
      "Scale item (chaos, pile)": "Escalar elemento (caos, montón)",
      "Click": "Clic",
      "Ctrl+click": "Ctrl+clic",
      "Right-click": "Clic derecho",
      "Drag": "Arrastrar",
      "Mouse wheel": "Rueda del ratón",
      "Space": "Espacio",
      "Volume ±5": "Volumen ±5",
      "Remove": "Quitar",
      "Unknown": "Desconocido",
      "Off": "Desactivado",
      "off": "desactivado",
      "auto": "auto",
      "Max": "Máx.",
      "Mixed": "Mixto",
      "Random": "Aleatorio",
      "Performer": "Artista",
      "Studio": "Estudio",
      "Group": "Grupo",
      "Scene": "Escena",
      "Image": "Imagen",
      "Tag or folder": "Etiqueta o carpeta",
      "preview clips": "clips de vista previa",
      "endless": "sin fin",
      "The storm tab detects tempo and beats itself (a few seconds per song), and the song loops. New items load ahead and appear exactly on the beat. Automatic: calm parts every bar, medium every 2 beats, loud every beat – drops right away. With pulse, the stage pumps on every beat; flash and shake come with the waves. “New wave every” doesn't apply then.": "La pestaña storm detecta sola el tempo y los pulsos (unos segundos por canción) y la canción se repite en bucle. Los elementos nuevos se cargan por adelantado y aparecen exactamente en el pulso. Automático: partes tranquilas cada compás, medias cada 2 pulsos, fuertes cada pulso; los drops, de inmediato. Con pulso, el escenario late en cada pulso; el destello y la sacudida llegan con las oleadas. «Nueva oleada cada» no se aplica entonces.",
      "Loop videos (off = fade out after the end)": "Repetir vídeos en bucle (desactivado = se desvanecen al terminar)",
      "Rush": "Oleada",
      "any": "cualquiera",
      "SD (faster)": "SD (más rápido)",
      "HD (sharper)": "HD (más nítido)",
      "Typing shows matching niches, tags and creators live – click (or ↑/↓ + Enter) to add them. Several are possible; one of them is picked at random per fetch. Without a choice you get trending. RedGifs only plays in the storm tab.": "Al escribir se muestran en directo los nichos, etiquetas y creadores que coinciden: haz clic (o ↑/↓ + Intro) para añadirlos. Se pueden añadir varios; uno se elige al azar en cada obtención. Sin elección, obtienes tendencias. RedGifs solo se reproduce en la pestaña storm.",
      "HUD on/off": "HUD activado/desactivado",
      "Full videos at once": "Vídeos completos a la vez",
      "0 = automatic: Media Storm measures how quickly Stash still answers and plays as many full videos as the connection allows. Over plain HTTP, browsers keep only about 6 connections to one server – when they're all taken, Stash stops answering in this browser. Further videos play as preview clips (or show their cover).": "0 = automático: Media Storm mide con qué rapidez sigue respondiendo Stash y reproduce tantos vídeos completos como permita la conexión. Con HTTP simple, los navegadores solo mantienen unas 6 conexiones con un servidor; cuando están todas ocupadas, Stash deja de responder en este navegador. Los demás vídeos se reproducen como clips de vista previa (o muestran su portada).",
    },
    patterns: [
      ["Playlist “(.+)”", "Lista «$1»"],
      ["(.+) \\((scenes|images)\\)", "$1 ($2)"],
      ["up to (\\d+)p", "hasta $1p"],
      ["≥ (\\d+) min", "≥ $1 min"],
      ["(\\d+) performers", "$1 artistas"],
      ["On the beat (\\d+) new, max (\\d+) endless", "Al ritmo · $1 nuevos, máx. $2 · sin fin"],
      ["On the beat (\\d+) new, max (\\d+)", "Al ritmo · $1 nuevos, máx. $2"],
      ["Every (\\d+) s (\\d+) new, max (\\d+) endless", "Cada $1 s · $2 nuevos, máx. $3 · sin fin"],
      ["Every (\\d+) s (\\d+) new, max (\\d+)", "Cada $1 s · $2 nuevos, máx. $3"],
      ["(\\d+) % marker clips", "$1 % clips de marcadores"],
      ["Also active: (\\d+) tags? for scenes and images", "También activo: $1 etiqueta(s) para escenas e imágenes"],
      ["Also active: (\\d+) tags? for marker clips", "También activo: $1 etiqueta(s) para clips de marcadores"],
      ["(\\d+) marker tags? \\+sub", "$1 etiquetas de marcadores (con subetiquetas)"],
      ["(\\d+) marker tags?", "$1 etiquetas de marcadores"],
      ["(\\d+) % of the videos", "$1 % de los vídeos"],
      ["(\\d+) % videos, preview clips", "$1 % vídeos, clips de vista previa"],
      ["(\\d+) % videos", "$1 % vídeos"],
      ["(\\d+) % images, (\\d+) % videos", "$1 % imágenes, $2 % vídeos"],
      ["(\\d+) %, (.+)", "$1 %, $2"],
      ["(.+?), frame (.+)", "$1, marco $2"],
      ["Darkened (\\d+) %(.*)", "Oscurecido $1 %$2"],
      ["(\\d+) tags?", "$1 etiquetas"],
      ["without (\\d+)", "sin $1"],
      ["from (★+)", "desde $1"],
      ["(\\d+) saved", "$1 guardados"],
      ["(\\d+) s", "$1 s"],
      ["(\\d+) min", "$1 min"],
      ["level (\\d+)", "nivel $1"],
      ["every (\\d+) waves", "cada $1 oleadas"],
      ["(\\d+) % of items", "$1 % de los elementos"],
      ["(\\d+) px/s", "$1 px/s"],
      ["Volume (\\d+) ?%", "Volumen $1 %"],
      ["· (\\d+) Clips", "· $1 clips"],
      ["Mood “(.+)”", "Ambiente «$1»"],
      ["Preset “(.+)” deleted", "Preajuste «$1» eliminado"],
      ["Preset “(.+)” loaded", "Preajuste «$1» cargado"],
      ["Preset “(.+)” saved", "Preajuste «$1» guardado"],
      ["Song “(.+)” chosen", "Canción «$1» elegida"],
      ["On the beat: (.+) BPM", "Al ritmo: $1 BPM"],
      ["On the beat: detecting beats in “(.+)” …", "Al ritmo: detectando pulsos en «$1» …"],
      ["Imported into Stash ✓ \\((.+?) #(\\d+)\\)", "Importado en Stash ✓ ($1 #$2)"],
      ["Error while loading: (.+)", "Error al cargar: $1"],
      ["Background error: (.+)", "Error de fondo: $1"],
      ["Error: (.+)", "Error: $1"],
      ["Download failed: (.+)", "Falló la descarga: $1"],
      ["Saved, but importing into Stash failed: (.+)", "Guardado, pero falló la importación a Stash: $1"],
      ["GraphQL error: (.+)", "Error de GraphQL: $1"],
      ["Media Storm (\\d[\\d.]*)", "Media Storm $1"],
      ["([\\d.,]+) Tsd\\.", "$1 mil"],
      ["([\\d.,]+) Mio\\.", "$1 M"],
    ],
  };
})();
