// Media Storm in Polish. Loaded before mediaStorm.js; the English text as shown is the key.
// Patterns catch texts with numbers or names ($1, $2 … = the parts in brackets, translated too if they
// are in `texts`). The language follows Stash UI's choice, otherwise Stash's interface language.
(function () {
  window.MediaStormLocales = window.MediaStormLocales || {};
  window.MediaStormLocales["pl"] = {
    sep: ", ",
    texts: {
      "Media Storm": "Media Storm",
      "Storm": "Storm",
      "Ready": "Gotowe",
      "Running": "Działa",
      "Paused": "Wstrzymano",
      "Stopped": "Zatrzymano",
      "starts in its own tab": "uruchamia się w osobnej karcie",
      "Running in the storm tab": "Działa w karcie storm",
      "Start": "Start",
      "Stop": "Zatrzymaj",
      "Restart": "Uruchom ponownie",
      "Pause": "Pauza",
      "Pause / resume": "Pauza / wznów",
      "Pause / resume (Space)": "Pauza / wznów (Spacja)",
      "Next wave": "Następna fala",
      "Next wave now (N)": "Następna fala teraz (N)",
      "Next wave right away": "Następna fala od razu",
      "New wave": "Nowa fala",
      "Reroll background": "Wylosuj tło ponownie",
      "Reroll background (B)": "Wylosuj tło ponownie (B)",
      "Close (Esc)": "Zamknij (Esc)",
      "Close panel": "Zamknij panel",
      "Stop (Esc)": "Zatrzymaj (Esc)",
      "Settings (S)": "Ustawienia (S)",
      "Settings": "Ustawienia",
      "Fullscreen (F)": "Pełny ekran (F)",
      "Fullscreen": "Pełny ekran",
      "Fullscreen not allowed": "Pełny ekran niedozwolony",
      "Liquid glass": "Płynne szkło",
      "Back": "Wstecz",
      "Back to the overview (Esc)": "Wróć do przeglądu (Esc)",
      "Hotkeys & mouse": "Skróty i mysz",
      "Expand/collapse": "Rozwiń/zwiń",
      "Click or press a key for sound": "Kliknij lub naciśnij klawisz, aby włączyć dźwięk",
      "A freshly opened storm tab may only play sound after a click or key press.": "Świeżo otwarta karta storm może odtwarzać dźwięk dopiero po kliknięciu lub naciśnięciu klawisza.",
      "Nothing found": "Nic nie znaleziono",
      "With these filters there are no images or videos. Loosen tags, folders or rating – or reset everything.": "Przy tych filtrach nie ma obrazów ani filmów. Poluzuj tagi, foldery lub ocenę – albo zresetuj wszystko.",
      "Reset filters": "Resetuj filtry",
      "Filters reset – whole library": "Zresetowano filtry – cała biblioteka",
      "No media found for this source/filter": "Nie znaleziono mediów dla tego źródła/filtra",
      "First wave loading …": "Wczytywanie pierwszej fali …",
      "Searching …": "Szukanie …",
      "Error while loading:": "Błąd podczas wczytywania:",
      "Background error:": "Błąd tła:",
      "GraphQL error:": "Błąd GraphQL:",
      "Pop-up blocked – please allow pop-ups for Stash": "Wyskakujące okno zablokowane – zezwól na wyskakujące okna dla Stash",
      "Mood": "Nastrój",
      "Next mood": "Następny nastrój",
      "Default": "Domyślny",
      "Chaos as usual": "Chaos jak zwykle",
      "Chill": "Chill",
      "Pile, calm, breathing": "Stos, spokojnie, oddychając",
      "Fast, full, shaking": "Szybko, pełno, drżąco",
      "Gallery": "Galeria",
      "Mosaic, tidy": "Mozaika, uporządkowana",
      "Cinema": "Kino",
      "Spotlight, videos only": "Reflektor, tylko filmy",
      "Trip": "Trip",
      "Spiral, colors, 3D": "Spirala, kolory, 3D",
      "Ticker": "Ticker",
      "Polaroids drift by": "Polaroidy dryfują obok",
      "Rain": "Deszcz",
      "Falls through from the top": "Spada z góry",
      "Manga": "Manga",
      "Ink, halftone, impact": "Tusz, półton, uderzenie",
      "Neon": "Neon",
      "Glow, glitch, beat": "Poświata, glitch, rytm",
      "Tempo": "Tempo",
      "On the beat": "W rytmie",
      "Media": "Media",
      "Sound": "Dźwięk",
      "Layout": "Układ",
      "Layout:": "Układ:",
      "Effects": "Efekty",
      "Background": "Tło",
      "Source & filters": "Źródło i filtry",
      "Folders": "Foldery",
      "RedGifs": "RedGifs",
      "My presets": "Moje presety",
      "New wave every": "Nowa fala co",
      "Every": "Co",
      "Items per wave": "Elementy na falę",
      "First wave (right away)": "Pierwsza fala (od razu)",
      "At most at once": "Maksymalnie naraz",
      "Items / Maximum": "Elementy / Maksimum",
      "Endless – replace the oldest items instead of stopping": "Bez końca – zastępuje najstarsze elementy zamiast się zatrzymać",
      "Waves on the beat of a song": "Fale w rytmie piosenki",
      "Choose song …": "Wybierz piosenkę …",
      "No song yet": "Brak piosenki",
      "No song chosen": "Nie wybrano piosenki",
      "Song volume": "Głośność piosenki",
      "Every 2 beats": "Co 2 uderzenia",
      "Every bar (4 beats)": "Każdy takt (4 uderzenia)",
      "Every 2 bars": "Co 2 takty",
      "On every beat": "Na każdym uderzeniu",
      "Couldn't save the song (storage blocked?)": "Nie udało się zapisać piosenki (pamięć zablokowana?)",
      "On the beat: click or press a key to start the music": "W rytmie: kliknij lub naciśnij klawisz, aby rozpocząć muzykę",
      "On the beat: couldn't read the song": "W rytmie: nie udało się odczytać piosenki",
      "On the beat: no song chosen yet (panel → On the beat) – waves run by time": "W rytmie: nie wybrano jeszcze piosenki (panel → W rytmie) – fale działają według czasu",
      "Images": "Obrazy",
      "Videos": "Filmy",
      "Mix": "Mieszane",
      "Video source": "Źródło filmów",
      "Full video": "Cały film",
      "Preview clip (lighter)": "Klip podglądu (lżejszy)",
      "Image quality": "Jakość obrazu",
      "Thumbnail (faster)": "Miniatura (szybciej)",
      "Original": "Oryginał",
      "Random start": "Losowy start",
      "Random start point in the video": "Losowy punkt startu w filmie",
      "Ken Burns zoom on images": "Zoom Ken Burns na obrazach",
      "Volume": "Głośność",
      "Audible": "Słyszalne",
      "all videos": "wszystkie filmy",
      "All videos": "Wszystkie filmy",
      "under the mouse": "pod myszą",
      "Only under the mouse": "Tylko pod myszą",
      "newest video": "najnowszy film",
      "Only the newest video": "Tylko najnowszy film",
      "muted": "wyciszone",
      "Muted": "Wyciszone",
      "Automatic by loudness": "Automatycznie według głośności",
      "Chaos": "Chaos",
      "Pile": "Stos",
      "Grid": "Siatka",
      "Mosaic": "Mozaika",
      "Spotlight": "Reflektor",
      "Spiral": "Spirala",
      "Scattered everywhere. Drag to move, mouse wheel to scale.": "Rozrzucone wszędzie. Przeciągnij, aby przesunąć, kółko myszy zmienia rozmiar.",
      "Like photos on a table, heaped towards the middle.": "Jak zdjęcia na stole, usypane ku środkowi.",
      "Fixed cells that fill the whole screen.": "Stałe komórki wypełniające cały ekran.",
      "Pinboard columns: new items come in at the top, the rest slides down.": "Kolumny tablicy korkowej: nowe elementy wchodzą na górze, reszta zsuwa się w dół.",
      "The newest item big in the middle, the older ones in a circle around it.": "Najnowszy element duży pośrodku, starsze w kręgu wokół niego.",
      "Sunflower spiral with the newest item in the middle – every wave turns everything further.": "Spirala słonecznika z najnowszym elementem pośrodku – każda fala obraca wszystko dalej.",
      "Lanes from right to left. Items that have passed make room for new ones.": "Pasy od prawej do lewej. Elementy, które minęły, ustępują miejsca nowym.",
      "Falls through from the top. At the bottom, items make room for new ones.": "Spada z góry. Na dole elementy ustępują miejsca nowym.",
      "Avoid overlap – free spots first": "Unikaj nakładania się – najpierw wolne miejsca",
      "Size min": "Rozmiar min.",
      "Size max": "Rozmiar maks.",
      "Rotation": "Obrót",
      "Spacing": "Odstęp",
      "Columns": "Kolumny",
      "Speed": "Prędkość",
      "Frame": "Ramka",
      "Soft": "Miękka",
      "None": "Brak",
      "Polaroid": "Polaroid",
      "Circle": "Koło",
      "Square": "Kwadrat",
      "Shape": "Kształt",
      "Format": "Format",
      "Landscape 16:9": "Poziomo 16:9",
      "Portrait 3:4": "Pionowo 3:4",
      "Appear": "Pojawianie się",
      "Zoom": "Zoom",
      "Fade in": "Pojawianie",
      "Fade in and out": "Pojawianie i znikanie",
      "Slam": "Uderzenie",
      "Flip": "Obrót",
      "Fall": "Spadanie",
      "Spin": "Wirowanie",
      "Glitch start": "Start z glitchem",
      "Motion": "Ruch",
      "Drift": "Dryf",
      "Breathe": "Oddychanie",
      "Wobble": "Chybotanie",
      "Hold still": "Bez ruchu",
      "Pulse": "Puls",
      "Color rush": "Wir kolorów",
      "Glitch": "Glitch",
      "Blending": "Mieszanie",
      "Normal": "Normalne",
      "Double exposure": "Podwójna ekspozycja",
      "Negative": "Negatyw",
      "Negative rush": "Wir negatywu",
      "Texture": "Tekstura",
      "Film grain": "Ziarno filmowe",
      "Halftone": "Półton",
      "Vignette": "Winieta",
      "3D depth – parallax with the mouse": "Głębia 3D – paralaksa z myszą",
      "Reflection": "Odbicie",
      "Reflection under every item": "Odbicie pod każdym elementem",
      "Shake": "Drżenie",
      "Flash": "Błysk",
      "The flash is gentle and comes at most once per wave.": "Błysk jest łagodny i pojawia się najwyżej raz na falę.",
      "Just zoom and fade": "Tylko zoom i zanikanie",
      "Darken": "Przyciemnij",
      "Blur": "Rozmycie",
      "soft": "miękkie",
      "rerolls itself": "losuje się samo",
      "New background": "Nowe tło",
      "Reroll automatically": "Losuj automatycznie",
      "On every new wave": "Przy każdej nowej fali",
      "Artwork in the design": "Grafiki w projekcie",
      "Show images in the panel and at the start": "Pokaż obrazy w panelu i na starcie",
      "e.g. Artwork": "np. Artwork",
      "Uses images and scene screenshots with this tag and from folders with the same name. Click the cover for the next image.": "Używa obrazów i zrzutów ekranu scen z tym tagiem oraz z folderów o tej samej nazwie. Kliknij okładkę, aby zobaczyć następny obraz.",
      "Next image": "Następny obraz",
      "No background images found (tag “background”)": "Nie znaleziono obrazów tła (tag „background”)",
      "The Random Backgrounds plugin is not active": "Wtyczka Random Backgrounds nie jest aktywna",
      "plugin not active": "wtyczka nieaktywna",
      "Source": "Źródło",
      "Whole library": "Cała biblioteka",
      "Current page": "Bieżąca strona",
      "Current page (performer/tag/…)": "Bieżąca strona (wykonawca/tag/…)",
      "“Current page” uses the performer, tag, studio, gallery or group page you start from. On tag pages, your own tags always all have to match.": "„Bieżąca strona” używa strony wykonawcy, tagu, studia, galerii lub grupy, z której startujesz. Na stronach tagów Twoje własne tagi muszą pasować wszystkie.",
      "Not a performer/tag/studio/gallery/group page – using the whole library": "To nie strona wykonawcy/tagu/studia/galerii/grupy – używana jest cała biblioteka",
      "Only with tags": "Tylko z tagami",
      "Exclude tags": "Wyklucz tagi",
      "Marker clips": "Klipy znaczników",
      "Marker clips are the short moments you marked in your scenes. This share of the videos plays them (only the marked part, looping) instead of whole scenes. Choose which markers under Source & filters.": "Klipy znaczników to krótkie momenty oznaczone w scenach. Ten udział filmów odtwarza je (tylko oznaczoną część, w pętli) zamiast całych scen. Które znaczniki – wybierz w Źródło i filtry.",
      "Only marker clips with tags": "Tylko klipy znaczników z tagami",
      "Needs a share of marker clips under Media. Primary or extra tag of the marker; the filters above apply to the marker's scene.": "Wymaga udziału klipów znaczników w Media. Tag główny lub dodatkowy znacznika; filtry powyżej dotyczą sceny znacznika.",
      "All tags must match": "Wszystkie tagi muszą pasować",
      "Including sub-tags (recursive)": "Uwzględnij podtagi (rekurencyjnie)",
      "On tag pages, all chosen tags must match": "Na stronach tagów wszystkie wybrane tagi muszą pasować",
      "Minimum rating": "Minimalna ocena",
      "Only with favorite performers": "Tylko z ulubionymi wykonawcami",
      "favorites": "ulubione",
      "Search tag…": "Szukaj tagu…",
      "No tags found": "Nie znaleziono tagów",
      "A playlist (from Stash UI)": "Playlista (ze Stash UI)",
      "Playlist": "Playlista",
      "A playlist": "Playlista",
      "No playlists yet": "Brak playlist",
      "Stash UI's smart playlists: set filters in Scenes or Images there and press “Save as playlist”. The playlist decides – the filters below don't apply.": "Inteligentne playlisty Stash UI: ustaw tam filtry w Scenach lub Obrazach i naciśnij „Zapisz jako playlistę”. Decyduje playlista – filtry poniżej nie obowiązują.",
      "Only with performers": "Tylko z wykonawcami",
      "All performers must be in it": "Wszyscy wykonawcy muszą w nim być",
      "Search performer…": "Szukaj wykonawcy…",
      "No performers found": "Nie znaleziono wykonawców",
      "Resolution up to": "Rozdzielczość do",
      "Videos at least": "Filmy co najmniej",
      "any length": "dowolna długość",
      "1 min": "1 min",
      "5 min": "5 min",
      "20 min": "20 min",
      "A lower resolution runs smoother – 4K videos take the most.": "Niższa rozdzielczość działa płynniej – filmy 4K obciążają najbardziej.",
      "All folders": "Wszystkie foldery",
      "Filter folders…": "Filtruj foldery…",
      "Loading folders…": "Wczytywanie folderów…",
      "No folders found": "Nie znaleziono folderów",
      "Without a choice, the whole library is used. Subfolders are always included. Numbers: images (I) and videos (V).": "Bez wyboru używana jest cała biblioteka. Podfoldery są zawsze uwzględniane. Liczby: obrazy (I) i filmy (V).",
      "RedGifs share": "Udział RedGifs",
      "Niches, tags & creators": "Nisze, tagi i twórcy",
      "Search niches, tags, creators …": "Szukaj nisz, tagów, twórców …",
      "Niche": "Nisza",
      "Niches": "Nisze",
      "Tag": "Tag",
      "Tags": "Tagi",
      "Creator": "Twórca",
      "Verified": "Zweryfikowany",
      "Trending": "Popularne",
      "Top of the week": "Najlepsze tygodnia",
      "Top of the month": "Najlepsze miesiąca",
      "Top (all time)": "Najlepsze (wszech czasów)",
      "Latest": "Najnowsze",
      "Sort order": "Kolejność sortowania",
      "Quality": "Jakość",
      "Saving (⬇ on hover or key D)": "Zapis (⬇ po najechaniu lub klawisz D)",
      "Save location": "Miejsce zapisu",
      "Everything in one folder": "Wszystko w jednym folderze",
      "By source (niche/tag/creator)": "Według źródła (nisza/tag/twórca)",
      "By the clip's creator": "Według twórcy klipu",
      "Always saved in HD. If the save location is inside your Stash library, Stash scans the folder right away and the scene gets the link, title and the tag “RedGifs”.": "Zawsze zapisywane w HD. Jeśli miejsce zapisu jest w Twojej bibliotece Stash, Stash od razu skanuje folder, a scena dostaje link, tytuł i tag „RedGifs”.",
      "Save the RedGifs clip under the mouse to Stash": "Zapisz w Stash klip RedGifs pod myszą",
      "Hover over a RedGifs clip, then press D": "Najedź na klip RedGifs, potem naciśnij D",
      "Save to Stash (D)": "Zapisz w Stash (D)",
      "Open in Stash or on RedGifs": "Otwórz w Stash lub na RedGifs",
      "Open in Stash (Ctrl+click)": "Otwórz w Stash (Ctrl+klik)",
      "Open on RedGifs (Ctrl+click)": "Otwórz na RedGifs (Ctrl+klik)",
      "Already saved": "Już zapisano",
      "Already there": "Już jest",
      "Saved": "Zapisano",
      "Saved – Stash is still scanning, the scene will appear shortly": "Zapisano – Stash jeszcze skanuje, scena wkrótce się pojawi",
      "Saved, but importing into Stash failed:": "Zapisano, ale import do Stash nie powiódł się:",
      "Download failed:": "Pobieranie nie powiodło się:",
      "Failed – try again": "Niepowodzenie – spróbuj ponownie",
      "Authentication failed": "Uwierzytelnianie nie powiodło się",
      "creator not found": "nie znaleziono twórcy",
      "not found": "nie znaleziono",
      "no Stash library configured": "nie skonfigurowano biblioteki Stash",
      "no answer from the plugin backend": "brak odpowiedzi z backendu wtyczki",
      "Preset": "Preset",
      "Name for a new preset": "Nazwa nowego presetu",
      "A preset of your own saves all settings, including source, filters and RedGifs.": "Własny preset zapisuje wszystkie ustawienia, także źródło, filtry i RedGifs.",
      "Save": "Zapisz",
      "Load": "Wczytaj",
      "Delete": "Usuń",
      "None yet": "Brak",
      "Reset everything to defaults": "Przywróć wszystko do domyślnych",
      "Settings reset": "Zresetowano ustawienia",
      "Sleep timer": "Wyłącznik czasowy",
      "Sleep timer ran out – good night": "Wyłącznik czasowy dobiegł końca – dobranoc",
      "The sleep timer stops with a fade-out and closes the storm tab.": "Wyłącznik czasowy zatrzymuje z wyciszeniem i zamyka kartę storm.",
      "Afterwards": "Potem",
      "This panel": "Ten panel",
      "Show the HUD in the storm tab": "Pokaż HUD w karcie storm",
      "Show item big": "Pokaż element w dużym rozmiarze",
      "Remove item": "Usuń element",
      "Remove (right-click)": "Usuń (prawy przycisk)",
      "Remove all items": "Usuń wszystkie elementy",
      "Stop everything (with fade-out)": "Zatrzymaj wszystko (z wyciszeniem)",
      "Change layout": "Zmień układ",
      "Move item (chaos, pile)": "Przesuń element (chaos, stos)",
      "Scale item (chaos, pile)": "Skaluj element (chaos, stos)",
      "Click": "Kliknięcie",
      "Ctrl+click": "Ctrl+klik",
      "Right-click": "Prawy przycisk",
      "Drag": "Przeciągnięcie",
      "Mouse wheel": "Kółko myszy",
      "Space": "Spacja",
      "Volume ±5": "Głośność ±5",
      "Remove": "Usuń",
      "Unknown": "Nieznane",
      "Off": "Wył.",
      "off": "wył.",
      "auto": "auto",
      "Max": "Maks.",
      "Mixed": "Mieszane",
      "Random": "Losowo",
      "Performer": "Wykonawca",
      "Studio": "Studio",
      "Group": "Grupa",
      "Scene": "Scena",
      "Image": "Obraz",
      "Tag or folder": "Tag lub folder",
      "preview clips": "klipy podglądu",
      "endless": "bez końca",
      "The storm tab detects tempo and beats itself (a few seconds per song), and the song loops. New items load ahead and appear exactly on the beat. Automatic: calm parts every bar, medium every 2 beats, loud every beat – drops right away. With pulse, the stage pumps on every beat; flash and shake come with the waves. “New wave every” doesn't apply then.": "Karta storm sama wykrywa tempo i uderzenia (kilka sekund na piosenkę), a piosenka gra w pętli. Nowe elementy ładują się z wyprzedzeniem i pojawiają się dokładnie w rytmie. Automatycznie: spokojne fragmenty co takt, średnie co 2 uderzenia, głośne co uderzenie – dropy od razu. Z pulsem scena pulsuje na każdym uderzeniu; błysk i drżenie przychodzą z falami. „Nowa fala co” wtedy nie obowiązuje.",
      "Loop videos (off = fade out after the end)": "Zapętlaj filmy (wył. = wyciszenie po zakończeniu)",
      "Rush": "Wir",
      "any": "dowolne",
      "SD (faster)": "SD (szybciej)",
      "HD (sharper)": "HD (ostrzej)",
      "Typing shows matching niches, tags and creators live – click (or ↑/↓ + Enter) to add them. Several are possible; one of them is picked at random per fetch. Without a choice you get trending. RedGifs only plays in the storm tab.": "Podczas pisania na żywo pojawiają się pasujące nisze, tagi i twórcy – kliknij (lub ↑/↓ + Enter), aby je dodać. Można dodać kilka; przy każdym pobraniu losowany jest jeden z nich. Bez wyboru dostajesz popularne. RedGifs gra tylko w karcie storm.",
      "HUD on/off": "HUD wł./wył.",
      "Full videos at once": "Pełne filmy naraz",
      "0 = automatic: Media Storm measures how quickly Stash still answers and plays as many full videos as the connection allows. Over plain HTTP, browsers keep only about 6 connections to one server – when they're all taken, Stash stops answering in this browser. Further videos play as preview clips (or show their cover).": "0 = automatycznie: Media Storm mierzy, jak szybko Stash jeszcze odpowiada, i odtwarza tyle pełnych filmów, na ile pozwala połączenie. Przy zwykłym HTTP przeglądarki utrzymują tylko około 6 połączeń z jednym serwerem – gdy wszystkie są zajęte, Stash przestaje odpowiadać w tej przeglądarce. Dalsze filmy odtwarzają się jako klipy podglądu (lub pokazują okładkę).",
    },
    patterns: [
      ["Playlist “(.+)”", "Playlista „$1”"],
      ["(.+) \\((scenes|images)\\)", "$1 ($2)"],
      ["up to (\\d+)p", "do $1p"],
      ["≥ (\\d+) min", "≥ $1 min"],
      ["(\\d+) performers", "Wykonawcy: $1"],
      ["On the beat (\\d+) new, max (\\d+) endless", "W rytmie · $1 nowych, maks. $2 · bez końca"],
      ["On the beat (\\d+) new, max (\\d+)", "W rytmie · $1 nowych, maks. $2"],
      ["Every (\\d+) s (\\d+) new, max (\\d+) endless", "Co $1 s · $2 nowych, maks. $3 · bez końca"],
      ["Every (\\d+) s (\\d+) new, max (\\d+)", "Co $1 s · $2 nowych, maks. $3"],
      ["(\\d+) % marker clips", "$1 % klipów znaczników"],
      ["(\\d+) marker tags? \\+sub", "Tagi znaczników: $1 (z podtagami)"],
      ["(\\d+) marker tags?", "Tagi znaczników: $1"],
      ["(\\d+) % of the videos", "$1 % filmów"],
      ["(\\d+) % videos, preview clips", "$1 % filmów, klipy podglądu"],
      ["(\\d+) % videos", "$1 % filmów"],
      ["(\\d+) % images, (\\d+) % videos", "$1 % obrazów, $2 % filmów"],
      ["(\\d+) %, (.+)", "$1 %, $2"],
      ["(.+?), frame (.+)", "$1, ramka $2"],
      ["Darkened (\\d+) %(.*)", "Przyciemniono $1 %$2"],
      ["(\\d+) tags?", "Tagi: $1"],
      ["without (\\d+)", "bez: $1"],
      ["from (★+)", "od $1"],
      ["(\\d+) saved", "zapisano: $1"],
      ["(\\d+) s", "$1 s"],
      ["(\\d+) min", "$1 min"],
      ["level (\\d+)", "poziom $1"],
      ["every (\\d+) waves", "co $1 fal"],
      ["(\\d+) % of items", "$1 % elementów"],
      ["(\\d+) px/s", "$1 px/s"],
      ["Volume (\\d+) ?%", "Głośność $1%"],
      ["· (\\d+) Clips", "· klipy: $1"],
      ["Mood “(.+)”", "Nastrój „$1”"],
      ["Preset “(.+)” deleted", "Usunięto preset „$1”"],
      ["Preset “(.+)” loaded", "Wczytano preset „$1”"],
      ["Preset “(.+)” saved", "Zapisano preset „$1”"],
      ["Song “(.+)” chosen", "Wybrano piosenkę „$1”"],
      ["On the beat: (.+) BPM", "W rytmie: $1 BPM"],
      ["On the beat: detecting beats in “(.+)” …", "W rytmie: wykrywanie uderzeń w „$1” …"],
      ["Imported into Stash ✓ \\((.+?) #(\\d+)\\)", "Zaimportowano do Stash ✓ ($1 #$2)"],
      ["Error while loading: (.+)", "Błąd podczas wczytywania: $1"],
      ["Background error: (.+)", "Błąd tła: $1"],
      ["Error: (.+)", "Błąd: $1"],
      ["Download failed: (.+)", "Pobieranie nie powiodło się: $1"],
      ["Saved, but importing into Stash failed: (.+)", "Zapisano, ale import do Stash nie powiódł się: $1"],
      ["GraphQL error: (.+)", "Błąd GraphQL: $1"],
      ["Media Storm (\\d[\\d.]*)", "Media Storm $1"],
      ["([\\d.,]+) Tsd\\.", "$1 tys."],
      ["([\\d.,]+) Mio\\.", "$1 mln"],
    ],
  };
})();
