// Media Storm in Japanese. Loaded before mediaStorm.js; the English text as shown is the key.
// Patterns catch texts with numbers or names ($1, $2 … = the parts in brackets, translated too if they
// are in `texts`). The language follows Stash UI's choice, otherwise Stash's interface language.
(function () {
  window.MediaStormLocales = window.MediaStormLocales || {};
  window.MediaStormLocales["ja"] = {
    sep: "、",
    texts: {
      "Media Storm": "Media Storm",
      "Storm": "ストーム",
      "Ready": "準備完了",
      "Running": "実行中",
      "Paused": "一時停止中",
      "Stopped": "停止しました",
      "starts in its own tab": "専用のタブで開始します",
      "Running in the storm tab": "ストームタブで実行中",
      "Start": "開始",
      "Stop": "停止",
      "Restart": "再開始",
      "Pause": "一時停止",
      "Pause / resume": "一時停止 / 再開",
      "Pause / resume (Space)": "一時停止 / 再開 (スペース)",
      "Next wave": "次のウェーブ",
      "Next wave now (N)": "今すぐ次のウェーブ (N)",
      "Next wave right away": "すぐに次のウェーブ",
      "New wave": "新しいウェーブ",
      "Reroll background": "背景を再抽選",
      "Reroll background (B)": "背景を再抽選 (B)",
      "Close (Esc)": "閉じる (Esc)",
      "Close panel": "パネルを閉じる",
      "Stop (Esc)": "停止 (Esc)",
      "Settings (S)": "設定 (S)",
      "Settings": "設定",
      "Fullscreen (F)": "全画面 (F)",
      "Fullscreen": "全画面",
      "Fullscreen not allowed": "全画面は許可されていません",
      "Liquid glass": "リキッドグラス",
      "Back": "戻る",
      "Back to the overview (Esc)": "概要に戻る (Esc)",
      "Hotkeys & mouse": "ホットキーとマウス",
      "Expand/collapse": "展開/折りたたみ",
      "Click or press a key for sound": "クリックまたはキー操作で音を出します",
      "A freshly opened storm tab may only play sound after a click or key press.": "開いたばかりのストームタブは、クリックまたはキー操作のあとでないと音が出ない場合があります。",
      "Nothing found": "何も見つかりません",
      "With these filters there are no images or videos. Loosen tags, folders or rating – or reset everything.": "これらのフィルターでは画像も動画もありません。タグ、フォルダ、評価を緩めるか、すべてリセットしてください。",
      "Reset filters": "フィルターをリセット",
      "Filters reset – whole library": "フィルターをリセットしました – ライブラリ全体",
      "No media found for this source/filter": "このソース/フィルターではメディアが見つかりません",
      "First wave loading …": "最初のウェーブを読み込み中 …",
      "Searching …": "検索中 …",
      "Error while loading:": "読み込み中のエラー:",
      "Background error:": "背景のエラー:",
      "GraphQL error:": "GraphQL エラー:",
      "Pop-up blocked – please allow pop-ups for Stash": "ポップアップがブロックされました – Stash のポップアップを許可してください",
      "Mood": "ムード",
      "Next mood": "次のムード",
      "Default": "デフォルト",
      "Chaos as usual": "いつも通りのカオス",
      "Chill": "チル",
      "Pile, calm, breathing": "積み重ね、穏やかに、呼吸するように",
      "Fast, full, shaking": "速く、満載で、揺れる",
      "Gallery": "ギャラリー",
      "Mosaic, tidy": "モザイク、整然と",
      "Cinema": "シネマ",
      "Spotlight, videos only": "スポットライト、動画のみ",
      "Trip": "トリップ",
      "Spiral, colors, 3D": "スパイラル、色、3D",
      "Ticker": "ティッカー",
      "Polaroids drift by": "ポラロイドが流れていく",
      "Rain": "レイン",
      "Falls through from the top": "上から降ってきます",
      "Manga": "マンガ",
      "Ink, halftone, impact": "インク、ハーフトーン、インパクト",
      "Neon": "ネオン",
      "Glow, glitch, beat": "グロー、グリッチ、ビート",
      "Tempo": "テンポ",
      "On the beat": "ビートに合わせて",
      "Media": "メディア",
      "Sound": "サウンド",
      "Layout": "レイアウト",
      "Layout:": "レイアウト:",
      "Effects": "エフェクト",
      "Background": "背景",
      "Source & filters": "ソースとフィルター",
      "Folders": "フォルダ",
      "RedGifs": "RedGifs",
      "My presets": "マイプリセット",
      "New wave every": "新しいウェーブの間隔",
      "Every": "間隔",
      "Items per wave": "ウェーブあたりの項目数",
      "First wave (right away)": "最初のウェーブ (すぐに)",
      "At most at once": "同時表示の最大数",
      "Items / Maximum": "項目 / 最大",
      "Endless – replace the oldest items instead of stopping": "エンドレス – 停止せず、最も古い項目を置き換えます",
      "Waves on the beat of a song": "曲のビートに合わせたウェーブ",
      "Choose song …": "曲を選択 …",
      "No song yet": "まだ曲がありません",
      "No song chosen": "曲が選ばれていません",
      "Song volume": "曲の音量",
      "Every 2 beats": "2 ビートごと",
      "Every bar (4 beats)": "小節ごと (4 ビート)",
      "Every 2 bars": "2 小節ごと",
      "On every beat": "毎ビート",
      "Couldn't save the song (storage blocked?)": "曲を保存できませんでした (ストレージがブロックされている?)",
      "On the beat: click or press a key to start the music": "ビートに合わせて: クリックまたはキー操作で音楽を開始します",
      "On the beat: couldn't read the song": "ビートに合わせて: 曲を読み取れませんでした",
      "On the beat: no song chosen yet (panel → On the beat) – waves run by time": "ビートに合わせて: まだ曲が選ばれていません (パネル → ビートに合わせて) – ウェーブは時間で動きます",
      "Images": "画像",
      "Videos": "動画",
      "Mix": "ミックス",
      "Video source": "動画ソース",
      "Full video": "動画全体",
      "Preview clip (lighter)": "プレビュークリップ (軽量)",
      "Image quality": "画像品質",
      "Thumbnail (faster)": "サムネイル (高速)",
      "Original": "オリジナル",
      "Random start": "ランダム開始",
      "Random start point in the video": "動画内のランダムな開始位置",
      "Ken Burns zoom on images": "画像にケン・バーンズ効果のズーム",
      "Volume": "音量",
      "Audible": "音あり",
      "all videos": "すべての動画",
      "All videos": "すべての動画",
      "under the mouse": "マウスの下",
      "Only under the mouse": "マウスの下のみ",
      "newest video": "最新の動画",
      "Only the newest video": "最新の動画のみ",
      "muted": "ミュート",
      "Muted": "ミュート",
      "Automatic by loudness": "音量に応じて自動",
      "Chaos": "カオス",
      "Pile": "山積み",
      "Grid": "グリッド",
      "Mosaic": "モザイク",
      "Spotlight": "スポットライト",
      "Spiral": "スパイラル",
      "Scattered everywhere. Drag to move, mouse wheel to scale.": "あちこちに散らばります。ドラッグで移動、マウスホイールで拡大縮小。",
      "Like photos on a table, heaped towards the middle.": "テーブルの上の写真のように、中央に向かって積み重なります。",
      "Fixed cells that fill the whole screen.": "画面全体を埋める固定のセル。",
      "Pinboard columns: new items come in at the top, the rest slides down.": "コルクボードの列: 新しい項目は上から入り、残りは下へずれます。",
      "The newest item big in the middle, the older ones in a circle around it.": "最新の項目を中央に大きく、古いものはその周りに円状に。",
      "Sunflower spiral with the newest item in the middle – every wave turns everything further.": "中央に最新の項目を置くひまわり型スパイラル – ウェーブごとにすべてがさらに回転します。",
      "Lanes from right to left. Items that have passed make room for new ones.": "右から左へ流れるレーン。通り過ぎた項目は新しい項目に場所を譲ります。",
      "Falls through from the top. At the bottom, items make room for new ones.": "上から降ってきます。下に着いた項目は新しい項目に場所を譲ります。",
      "Avoid overlap – free spots first": "重なりを避ける – まず空いている場所へ",
      "Size min": "最小サイズ",
      "Size max": "最大サイズ",
      "Rotation": "回転",
      "Spacing": "間隔",
      "Columns": "列",
      "Speed": "速度",
      "Frame": "フレーム",
      "Soft": "ソフト",
      "None": "なし",
      "Polaroid": "ポラロイド",
      "Circle": "円",
      "Square": "正方形",
      "Shape": "形",
      "Format": "フォーマット",
      "Landscape 16:9": "横 16:9",
      "Portrait 3:4": "縦 3:4",
      "Appear": "登場",
      "Zoom": "ズーム",
      "Fade in": "フェードイン",
      "Fade in and out": "フェードイン/アウト",
      "Slam": "スラム",
      "Flip": "フリップ",
      "Fall": "落下",
      "Spin": "スピン",
      "Glitch start": "グリッチ開始",
      "Motion": "動き",
      "Drift": "ドリフト",
      "Breathe": "呼吸",
      "Wobble": "ぐらつき",
      "Hold still": "静止",
      "Pulse": "パルス",
      "Color rush": "カラーラッシュ",
      "Glitch": "グリッチ",
      "Blending": "ブレンド",
      "Normal": "通常",
      "Double exposure": "二重露光",
      "Negative": "ネガ",
      "Negative rush": "ネガラッシュ",
      "Texture": "テクスチャ",
      "Film grain": "フィルムグレイン",
      "Halftone": "ハーフトーン",
      "Vignette": "ビネット",
      "3D depth – parallax with the mouse": "3D 奥行き – マウスでパララックス",
      "Reflection": "反射",
      "Reflection under every item": "すべての項目の下に反射",
      "Shake": "シェイク",
      "Flash": "フラッシュ",
      "The flash is gentle and comes at most once per wave.": "フラッシュは穏やかで、1 ウェーブにつき多くても 1 回です。",
      "Just zoom and fade": "ズームとフェードのみ",
      "Darken": "暗くする",
      "Blur": "ぼかし",
      "soft": "ソフト",
      "rerolls itself": "自動で再抽選",
      "New background": "新しい背景",
      "Reroll automatically": "自動で再抽選",
      "On every new wave": "新しいウェーブごと",
      "Artwork in the design": "デザイン内のアートワーク",
      "Show images in the panel and at the start": "パネルと開始時に画像を表示",
      "e.g. Artwork": "例: Artwork",
      "Uses images and scene screenshots with this tag and from folders with the same name. Click the cover for the next image.": "このタグが付いた画像とシーンのスクリーンショット、および同名のフォルダのものを使います。カバーをクリックすると次の画像になります。",
      "Next image": "次の画像",
      "No background images found (tag “background”)": "背景画像が見つかりません (タグ「background」)",
      "The Random Backgrounds plugin is not active": "Random Backgrounds プラグインが有効ではありません",
      "plugin not active": "プラグインが有効ではありません",
      "Source": "ソース",
      "Whole library": "ライブラリ全体",
      "Current page": "現在のページ",
      "Current page (performer/tag/…)": "現在のページ (パフォーマー/タグ/…)",
      "“Current page” uses the performer, tag, studio, gallery or group page you start from. On tag pages, your own tags always all have to match.": "「現在のページ」は、開始元のパフォーマー、タグ、スタジオ、ギャラリー、グループのページを使います。タグページでは、自分のタグはすべて一致する必要があります。",
      "Not a performer/tag/studio/gallery/group page – using the whole library": "パフォーマー/タグ/スタジオ/ギャラリー/グループのページではありません – ライブラリ全体を使います",
      "Only with tags": "これらのタグのみ",
      "Exclude tags": "タグを除外",
      "Marker clips": "マーカークリップ",
      "Marker clips are the short moments you marked in your scenes. This share of the videos plays them (only the marked part, looping) instead of whole scenes. Choose which markers under Source & filters.": "マーカークリップは、シーンにマークした短い瞬間です。動画のこの割合は、シーン全体の代わりにそれらを (マークした部分のみ、ループで) 再生します。どのマーカーを使うかは「ソースとフィルター」で選びます。",
      "Only marker clips with tags": "タグ付きのマーカークリップのみ",
      "Needs a share of marker clips under Media. Primary or extra tag of the marker; the filters above apply to the marker's scene.": "「メディア」でマーカークリップの割合が必要です。マーカーの主タグまたは追加タグが対象で、上のフィルターはマーカーのシーンに適用されます。",
      "All tags must match": "すべてのタグが一致する必要があります",
      "Including sub-tags (recursive)": "サブタグを含める (再帰)",
      "Tags apply to": "タグの適用先",
      "Scenes and images": "シーンと画像",
      "Only with tags (marker clips)": "このタグを持つもののみ（マーカークリップ）",
      "The tag box edits the kind chosen above; the other kind keeps its own tags. Marker clips need a share under Media – their tags are the marker's primary or extra tag, and the filters apply to the marker's scene too. Exclude tags and the two switches count for all kinds.": "タグ欄は上で選んだ種類を編集します。もう一方の種類は自分のタグを保持します。マーカークリップは「メディア」で割合の設定が必要です。そのタグはマーカーのメインタグまたは追加タグで、フィルターはマーカーのシーンにも適用されます。除外タグと2つのスイッチはすべての種類に効きます。",
      "On tag pages, all chosen tags must match": "タグページでは、選んだすべてのタグが一致する必要があります",
      "Minimum rating": "最低評価",
      "Only with favorite performers": "お気に入りのパフォーマーのみ",
      "favorites": "お気に入り",
      "Search tag…": "タグを検索…",
      "No tags found": "タグが見つかりません",
      "A playlist (from Stash UI)": "プレイリスト (Stash UI から)",
      "Playlist": "プレイリスト",
      "A playlist": "プレイリスト",
      "No playlists yet": "プレイリストはまだありません",
      "Stash UI's smart playlists: set filters in Scenes or Images there and press “Save as playlist”. The playlist decides – the filters below don't apply.": "Stash UI のスマートプレイリスト: そこでシーンまたは画像のフィルターを設定し、「プレイリストとして保存」を押してください。プレイリストが優先され、下のフィルターは適用されません。",
      "Only with performers": "これらのパフォーマーのみ",
      "All performers must be in it": "すべてのパフォーマーが含まれている必要があります",
      "Search performer…": "パフォーマーを検索…",
      "No performers found": "パフォーマーが見つかりません",
      "Resolution up to": "解像度の上限",
      "Videos at least": "動画の最小長",
      "any length": "任意の長さ",
      "1 min": "1 分",
      "5 min": "5 分",
      "20 min": "20 分",
      "A lower resolution runs smoother – 4K videos take the most.": "解像度が低いほど滑らかに動作します – 4K 動画が最も重くなります。",
      "All folders": "すべてのフォルダ",
      "Filter folders…": "フォルダを絞り込み…",
      "Loading folders…": "フォルダを読み込み中…",
      "No folders found": "フォルダが見つかりません",
      "Without a choice, the whole library is used. Subfolders are always included. Numbers: images (I) and videos (V).": "何も選ばなければライブラリ全体を使います。サブフォルダは常に含まれます。数字: 画像 (I) と動画 (V)。",
      "RedGifs share": "RedGifs の割合",
      "Niches, tags & creators": "ニッチ、タグ、クリエイター",
      "Search niches, tags, creators …": "ニッチ、タグ、クリエイターを検索 …",
      "Niche": "ニッチ",
      "Niches": "ニッチ",
      "Tag": "タグ",
      "Tags": "タグ",
      "Creator": "クリエイター",
      "Verified": "認証済み",
      "Trending": "トレンド",
      "Top of the week": "今週のトップ",
      "Top of the month": "今月のトップ",
      "Top (all time)": "トップ (全期間)",
      "Latest": "最新",
      "Sort order": "並べ替え",
      "Quality": "品質",
      "Saving (⬇ on hover or key D)": "保存 (ホバー時の ⬇ またはキー D)",
      "Save location": "保存先",
      "Everything in one folder": "すべて 1 つのフォルダに",
      "By source (niche/tag/creator)": "ソース別 (ニッチ/タグ/クリエイター)",
      "By the clip's creator": "クリップのクリエイター別",
      "Always saved in HD. If the save location is inside your Stash library, Stash scans the folder right away and the scene gets the link, title and the tag “RedGifs”.": "常に HD で保存されます。保存先が Stash ライブラリ内にある場合、Stash はすぐにフォルダをスキャンし、シーンにはリンク、タイトル、タグ「RedGifs」が付きます。",
      "Save the RedGifs clip under the mouse to Stash": "マウスの下の RedGifs クリップを Stash に保存",
      "Hover over a RedGifs clip, then press D": "RedGifs のクリップにマウスを重ねて D を押します",
      "Save to Stash (D)": "Stash に保存 (D)",
      "Open in Stash or on RedGifs": "Stash または RedGifs で開く",
      "Open in Stash (Ctrl+click)": "Stash で開く (Ctrl+クリック)",
      "Open on RedGifs (Ctrl+click)": "RedGifs で開く (Ctrl+クリック)",
      "Already saved": "すでに保存済み",
      "Already there": "すでにあります",
      "Saved": "保存しました",
      "Saved – Stash is still scanning, the scene will appear shortly": "保存しました – Stash がまだスキャン中で、シーンはまもなく表示されます",
      "Saved, but importing into Stash failed:": "保存しましたが、Stash へのインポートに失敗しました:",
      "Download failed:": "ダウンロードに失敗しました:",
      "Failed – try again": "失敗しました – もう一度試してください",
      "Authentication failed": "認証に失敗しました",
      "creator not found": "クリエイターが見つかりません",
      "not found": "見つかりません",
      "no Stash library configured": "Stash ライブラリが設定されていません",
      "no answer from the plugin backend": "プラグインのバックエンドから応答がありません",
      "Preset": "プリセット",
      "Name for a new preset": "新しいプリセットの名前",
      "A preset of your own saves all settings, including source, filters and RedGifs.": "自分のプリセットには、ソース、フィルター、RedGifs を含むすべての設定が保存されます。",
      "Save": "保存",
      "Load": "読み込み",
      "Delete": "削除",
      "None yet": "まだありません",
      "Reset everything to defaults": "すべてをデフォルトに戻す",
      "Settings reset": "設定をリセットしました",
      "Sleep timer": "スリープタイマー",
      "Sleep timer ran out – good night": "スリープタイマーが終了しました – おやすみなさい",
      "The sleep timer stops with a fade-out and closes the storm tab.": "スリープタイマーはフェードアウトして停止し、ストームタブを閉じます。",
      "Afterwards": "終了後",
      "This panel": "このパネル",
      "Show the HUD in the storm tab": "ストームタブに HUD を表示",
      "Show item big": "項目を大きく表示",
      "Remove item": "項目を削除",
      "Remove (right-click)": "削除 (右クリック)",
      "Remove all items": "すべての項目を削除",
      "Stop everything (with fade-out)": "すべて停止 (フェードアウト付き)",
      "Change layout": "レイアウトを変更",
      "Move item (chaos, pile)": "項目を移動 (カオス、山積み)",
      "Scale item (chaos, pile)": "項目を拡大縮小 (カオス、山積み)",
      "Click": "クリック",
      "Ctrl+click": "Ctrl+クリック",
      "Right-click": "右クリック",
      "Drag": "ドラッグ",
      "Mouse wheel": "マウスホイール",
      "Space": "スペース",
      "Volume ±5": "音量 ±5",
      "Remove": "削除",
      "Unknown": "不明",
      "Off": "オフ",
      "off": "オフ",
      "auto": "自動",
      "Max": "最大",
      "Mixed": "混合",
      "Random": "ランダム",
      "Performer": "パフォーマー",
      "Studio": "スタジオ",
      "Group": "グループ",
      "Scene": "シーン",
      "Image": "画像",
      "Tag or folder": "タグまたはフォルダ",
      "preview clips": "プレビュークリップ",
      "endless": "エンドレス",
      "The storm tab detects tempo and beats itself (a few seconds per song), and the song loops. New items load ahead and appear exactly on the beat. Automatic: calm parts every bar, medium every 2 beats, loud every beat – drops right away. With pulse, the stage pumps on every beat; flash and shake come with the waves. “New wave every” doesn't apply then.": "ストームタブはテンポとビートを自分で検出し (1 曲あたり数秒)、曲はループします。新しい項目は先読みされ、ちょうどビートに合わせて登場します。自動: 静かな部分は小節ごと、中程度は 2 ビートごと、大音量は毎ビート – ドロップはすぐに。パルスをオンにすると、ステージは毎ビートで脈打ち、フラッシュとシェイクはウェーブとともに来ます。その場合「新しいウェーブの間隔」は適用されません。",
      "Loop videos (off = fade out after the end)": "動画をループ再生 (オフ = 終了後にフェードアウト)",
      "Rush": "ラッシュ",
      "any": "指定なし",
      "SD (faster)": "SD (高速)",
      "HD (sharper)": "HD (高精細)",
      "Typing shows matching niches, tags and creators live – click (or ↑/↓ + Enter) to add them. Several are possible; one of them is picked at random per fetch. Without a choice you get trending. RedGifs only plays in the storm tab.": "入力すると一致するニッチ、タグ、クリエイターがリアルタイムで表示されます – クリックして (または ↑/↓ + Enter で) 追加します。複数追加でき、取得のたびにそのうち 1 つがランダムに選ばれます。何も選ばなければトレンドになります。RedGifs はストームタブでのみ再生されます。",
      "HUD on/off": "HUD オン/オフ",
      "Full videos at once": "同時に再生する動画全体",
      "0 = automatic: Media Storm measures how quickly Stash still answers and plays as many full videos as the connection allows. Over plain HTTP, browsers keep only about 6 connections to one server – when they're all taken, Stash stops answering in this browser. Further videos play as preview clips (or show their cover).": "0 = 自動: Media Storm は Stash がどれだけ速く応答できるかを測定し、接続が許す数だけ動画全体を再生します。通常の HTTP では、ブラウザは 1 つのサーバーへの接続を約 6 本しか保持しません – すべて使われると、Stash はこのブラウザで応答しなくなります。それ以上の動画はプレビュークリップとして再生されます (またはカバーを表示します)。",
    },
    patterns: [
      ["Playlist “(.+)”", "プレイリスト「$1」"],
      ["(.+) \\((scenes|images)\\)", "$1 ($2)"],
      ["up to (\\d+)p", "最大 $1p"],
      ["≥ (\\d+) min", "≥ $1 分"],
      ["(\\d+) performers", "パフォーマー $1 人"],
      ["On the beat (\\d+) new, max (\\d+) endless", "ビートに合わせて · ウェーブごとに $1 個、最大 $2 個 · エンドレス"],
      ["On the beat (\\d+) new, max (\\d+)", "ビートに合わせて · ウェーブごとに $1 個、最大 $2 個"],
      ["Every (\\d+) s (\\d+) new, max (\\d+) endless", "$1 秒ごと · ウェーブごとに $2 個、最大 $3 個 · エンドレス"],
      ["Every (\\d+) s (\\d+) new, max (\\d+)", "$1 秒ごと · ウェーブごとに $2 個、最大 $3 個"],
      ["(\\d+) % marker clips", "マーカークリップ $1 %"],
      ["Also active: (\\d+) tags? for scenes and images", "他にも有効: シーンと画像用のタグ $1 個"],
      ["Also active: (\\d+) tags? for marker clips", "他にも有効: マーカークリップ用のタグ $1 個"],
      ["(\\d+) marker tags? \\+sub", "マーカータグ $1 個 (サブタグ含む)"],
      ["(\\d+) marker tags?", "マーカータグ $1 個"],
      ["(\\d+) % of the videos", "動画の $1 %"],
      ["(\\d+) % videos, preview clips", "動画 $1 %、プレビュークリップ"],
      ["(\\d+) % videos", "動画 $1 %"],
      ["(\\d+) % images, (\\d+) % videos", "画像 $1 %、動画 $2 %"],
      ["(\\d+) %, (.+)", "$1 %、$2"],
      ["(.+?), frame (.+)", "$1、フレーム $2"],
      ["Darkened (\\d+) %(.*)", "$1 % 暗く$2"],
      ["(\\d+) tags?", "タグ $1 個"],
      ["without (\\d+)", "$1 個を除く"],
      ["from (★+)", "$1 以上"],
      ["(\\d+) saved", "$1 個保存済み"],
      ["(\\d+) s", "$1 秒"],
      ["(\\d+) min", "$1 分"],
      ["level (\\d+)", "レベル $1"],
      ["every (\\d+) waves", "$1 ウェーブごと"],
      ["(\\d+) % of items", "項目の $1 %"],
      ["(\\d+) px/s", "$1 ピクセル/秒"],
      ["Volume (\\d+) ?%", "音量 $1%"],
      ["· (\\d+) Clips", "· クリップ $1 個"],
      ["Mood “(.+)”", "ムード「$1」"],
      ["Preset “(.+)” deleted", "プリセット「$1」を削除しました"],
      ["Preset “(.+)” loaded", "プリセット「$1」を読み込みました"],
      ["Preset “(.+)” saved", "プリセット「$1」を保存しました"],
      ["Song “(.+)” chosen", "曲「$1」を選択しました"],
      ["On the beat: (.+) BPM", "ビートに合わせて: $1 BPM"],
      ["On the beat: detecting beats in “(.+)” …", "ビートに合わせて: 「$1」のビートを検出中 …"],
      ["Imported into Stash ✓ \\((.+?) #(\\d+)\\)", "Stash にインポートしました ✓ ($1 #$2)"],
      ["Error while loading: (.+)", "読み込み中のエラー: $1"],
      ["Background error: (.+)", "背景のエラー: $1"],
      ["Error: (.+)", "エラー: $1"],
      ["Download failed: (.+)", "ダウンロードに失敗しました: $1"],
      ["Saved, but importing into Stash failed: (.+)", "保存しましたが、Stash へのインポートに失敗しました: $1"],
      ["GraphQL error: (.+)", "GraphQL エラー: $1"],
      ["Media Storm (\\d[\\d.]*)", "Media Storm $1"],
      ["([\\d.,]+) Tsd\\.", "$1 千"],
      ["([\\d.,]+) Mio\\.", "$1 百万"],
    ],
  };
})();
