// Media Storm in Simplified Chinese. Loaded before mediaStorm.js; the English text as shown is the key.
// Patterns catch texts with numbers or names ($1, $2 … = the parts in brackets, translated too if they
// are in `texts`). The language follows Stash UI's choice, otherwise Stash's interface language.
(function () {
  window.MediaStormLocales = window.MediaStormLocales || {};
  window.MediaStormLocales["zh-CN"] = {
    texts: {
      "Media Storm": "媒体风暴",
      Storm: "风暴",
      Ready: "就绪",
      Running: "运行中",
      Paused: "已暂停",
      Stopped: "已停止",
      "starts in its own tab": "在单独的标签页中启动",
      "Running in the storm tab": "正在风暴标签页中运行",
      Start: "开始",
      Stop: "停止",
      Restart: "重新开始",
      Pause: "暂停",
      "Pause / resume": "暂停 / 继续",
      "Pause / resume (Space)": "暂停 / 继续（空格）",
      "Next wave": "下一波",
      "Next wave now (N)": "立即下一波（N）",
      "Next wave right away": "立即开始下一波",
      "New wave": "新一波",
      "Reroll background": "更换背景",
      "Reroll background (B)": "更换背景（B）",
      "Close (Esc)": "关闭（Esc）",
      "Close panel": "关闭面板",
      "Stop (Esc)": "停止（Esc）",
      "Settings (S)": "设置（S）",
      Settings: "设置",
      "Fullscreen (F)": "全屏（F）",
      Fullscreen: "全屏",
      "Fullscreen not allowed": "不允许全屏",
      "Liquid glass": "液态玻璃",
      "Back": "返回",
      "Back to the overview (Esc)": "返回概览（Esc）",
      "Hotkeys & mouse": "快捷键和鼠标",
      "Expand/collapse": "展开/折叠",
      "Click or press a key for sound": "点击或按任意键开启声音",
      "A freshly opened storm tab may only play sound after a click or key press.": "新打开的风暴标签页可能要在点击或按键后才会播放声音。",
      "Nothing found": "什么也没找到",
      "With these filters there are no images or videos. Loosen tags, folders or rating – or reset everything.": "在这些筛选条件下没有图片或视频。请放宽标签、文件夹或评分——或者全部重置。",
      "Reset filters": "重置筛选",
      "Filters reset – whole library": "筛选已重置——整个媒体库",
      "No media found for this source/filter": "此来源/筛选下没有找到媒体",
      "First wave loading …": "第一波加载中 …",
      "Searching …": "正在搜索 …",
      "Error while loading:": "加载出错：",
      "Background error:": "背景出错：",
      "GraphQL error:": "GraphQL 错误：",
      "Pop-up blocked – please allow pop-ups for Stash": "弹出窗口被阻止——请允许 Stash 打开弹出窗口",
      Mood: "氛围",
      "Next mood": "下一种氛围",
      Default: "默认",
      "Chaos as usual": "一如既往的混乱",
      Chill: "放松",
      "Pile, calm, breathing": "堆叠、平静、呼吸",
      "Fast, full, shaking": "快速、满屏、震动",
      Gallery: "图库",
      "Mosaic, tidy": "马赛克、整齐",
      Cinema: "影院",
      "Spotlight, videos only": "聚光灯、仅视频",
      Trip: "迷幻",
      "Spiral, colors, 3D": "螺旋、色彩、3D",
      Ticker: "滚动条",
      "Polaroids drift by": "拍立得缓缓飘过",
      Rain: "雨",
      "Falls through from the top": "从顶部落下",
      Manga: "漫画",
      "Ink, halftone, impact": "墨线、网点、冲击",
      Neon: "霓虹",
      "Glow, glitch, beat": "发光、故障、节拍",
      Tempo: "节奏",
      "On the beat": "随节拍",
      Media: "媒体",
      Sound: "声音",
      Layout: "布局",
      "Layout:": "布局：",
      Effects: "效果",
      Background: "背景",
      "Source & filters": "来源与筛选",
      Folders: "文件夹",
      RedGifs: "RedGifs",
      "My presets": "我的预设",
      "New wave every": "每隔多久一波",
      Every: "每隔",
      "Items per wave": "每波数量",
      "First wave (right away)": "第一波（立即）",
      "At most at once": "同时最多",
      "Items / Maximum": "数量 / 最大值",
      "Endless – replace the oldest items instead of stopping": "无尽——替换最旧的项目而不是停止",
      "Waves on the beat of a song": "随歌曲节拍出现新一波",
      "Choose song …": "选择歌曲 …",
      "No song yet": "还没有歌曲",
      "No song chosen": "未选择歌曲",
      "Song volume": "歌曲音量",
      "Every 2 beats": "每 2 拍",
      "Every bar (4 beats)": "每小节（4 拍）",
      "Every 2 bars": "每 2 小节",
      "On every beat": "每个节拍",
      "Couldn't save the song (storage blocked?)": "无法保存歌曲（存储被阻止？）",
      "On the beat: click or press a key to start the music": "随节拍：点击或按任意键开始播放音乐",
      "On the beat: couldn't read the song": "随节拍：无法读取歌曲",
      "On the beat: no song chosen yet (panel → On the beat) – waves run by time": "随节拍：还没有选择歌曲（面板 → 随节拍）——按时间出现新一波",
      Images: "图片",
      Videos: "视频",
      Mix: "混合",
      "Video source": "视频来源",
      "Full video": "完整视频",
      "Preview clip (lighter)": "预览片段（更轻量）",
      "Image quality": "图片质量",
      "Thumbnail (faster)": "缩略图（更快）",
      Original: "原图",
      "Random start": "随机起点",
      "Random start point in the video": "视频中的随机起始位置",
      "Ken Burns zoom on images": "图片的肯·伯恩斯缩放",
      Volume: "音量",
      Audible: "可听见的",
      "all videos": "所有视频",
      "All videos": "所有视频",
      "under the mouse": "鼠标下方",
      "Only under the mouse": "仅鼠标下方",
      "newest video": "最新视频",
      "Only the newest video": "仅最新视频",
      muted: "静音",
      Muted: "静音",
      "Automatic by loudness": "按响度自动",
      Chaos: "混乱",
      Pile: "堆叠",
      Grid: "网格",
      Mosaic: "马赛克",
      Spotlight: "聚光灯",
      Spiral: "螺旋",
      "Scattered everywhere. Drag to move, mouse wheel to scale.": "四处散落。拖动可移动，滚轮可缩放。",
      "Like photos on a table, heaped towards the middle.": "像桌上的照片一样，向中间堆叠。",
      "Fixed cells that fill the whole screen.": "固定的格子铺满整个屏幕。",
      "Pinboard columns: new items come in at the top, the rest slides down.": "图钉板式的列：新项目从顶部进入，其余向下滑动。",
      "The newest item big in the middle, the older ones in a circle around it.": "最新的项目大大地放在中间，较旧的围成一圈。",
      "Sunflower spiral with the newest item in the middle – every wave turns everything further.": "向日葵螺旋，最新的项目在中间——每一波都会让整体继续旋转。",
      "Lanes from right to left. Items that have passed make room for new ones.": "从右向左的轨道。经过的项目会为新项目让位。",
      "Falls through from the top. At the bottom, items make room for new ones.": "从顶部落下。到底部后为新项目让位。",
      "Avoid overlap – free spots first": "避免重叠——优先使用空位",
      "Size min": "最小尺寸",
      "Size max": "最大尺寸",
      Rotation: "旋转",
      Spacing: "间距",
      Columns: "列数",
      Speed: "速度",
      Frame: "边框",
      Soft: "柔和",
      None: "无",
      Polaroid: "拍立得",
      Circle: "圆形",
      Square: "方形",
      Shape: "形状",
      Format: "格式",
      "Landscape 16:9": "横屏 16:9",
      "Portrait 3:4": "竖屏 3:4",
      Appear: "出现方式",
      Zoom: "缩放",
      "Fade in": "淡入",
      "Fade in and out": "淡入淡出",
      Slam: "撞击",
      Flip: "翻转",
      Fall: "落下",
      Spin: "旋转",
      "Glitch start": "故障开场",
      Motion: "运动",
      Drift: "漂移",
      Breathe: "呼吸",
      Wobble: "摇摆",
      "Hold still": "保持静止",
      Pulse: "脉冲",
      "Color rush": "色彩冲击",
      Glitch: "故障",
      Blending: "混合模式",
      Normal: "正常",
      "Double exposure": "双重曝光",
      Negative: "负片",
      "Negative rush": "负片冲击",
      Texture: "质感",
      "Film grain": "胶片颗粒",
      Halftone: "网点",
      Vignette: "暗角",
      "3D depth – parallax with the mouse": "3D 纵深——随鼠标产生视差",
      Reflection: "倒影",
      "Reflection under every item": "每个项目下方的倒影",
      Shake: "震动",
      Flash: "闪光",
      "The flash is gentle and comes at most once per wave.": "闪光很柔和，每一波最多出现一次。",
      "Just zoom and fade": "仅缩放和淡入淡出",
      Darken: "变暗",
      Blur: "模糊",
      soft: "柔化",
      "rerolls itself": "自动更换",
      "New background": "新背景",
      "Reroll automatically": "自动更换",
      "On every new wave": "每一波都更换",
      "Artwork in the design": "设计中的插画",
      "Show images in the panel and at the start": "在面板和开始时显示图片",
      "e.g. Artwork": "例如 Artwork",
      "Uses images and scene screenshots with this tag and from folders with the same name. Click the cover for the next image.": "使用带有此标签的图片和场景截图，以及同名文件夹中的内容。点击封面可换下一张。",
      "Next image": "下一张图片",
      "No background images found (tag “background”)": "没有找到背景图片（标签“background”）",
      "The Random Backgrounds plugin is not active": "Random Backgrounds 插件未启用",
      "plugin not active": "插件未启用",
      Source: "来源",
      "Whole library": "整个媒体库",
      "Current page": "当前页面",
      "Current page (performer/tag/…)": "当前页面（演员/标签/…）",
      "“Current page” uses the performer, tag, studio, gallery or group page you start from. On tag pages, your own tags always all have to match.": "“当前页面”会使用你开始时所在的演员、标签、工作室、图库或分组页面。在标签页面上，你自己选择的标签必须全部匹配。",
      "Not a performer/tag/studio/gallery/group page – using the whole library": "不是演员/标签/工作室/图库/分组页面——将使用整个媒体库",
      "Only with tags": "仅包含标签",
      "Exclude tags": "排除标签",
      "Marker clips": "标记片段",
      "Marker clips are the short moments you marked in your scenes. This share of the videos plays them (only the marked part, looping) instead of whole scenes. Choose which markers under Source & filters.": "标记片段是你在场景中标记的短片段。视频中的这一比例会播放它们（仅播放标记的部分并循环），而不是整个场景。在“来源与筛选”中选择要使用的标记。",
      "Only marker clips with tags": "仅含这些标签的标记片段",
      "Needs a share of marker clips under Media. Primary or extra tag of the marker; the filters above apply to the marker's scene.": "需要先在“媒体”中设置标记片段的比例。匹配标记的主标签或附加标签；上面的筛选条件作用于标记所在的场景。",
      "All tags must match": "所有标签都必须匹配",
      "Including sub-tags (recursive)": "包含子标签（递归）",
      "Tags apply to": "标签应用于",
      "Scenes and images": "场景和图片",
      "Only with tags (marker clips)": "仅含这些标签（标记片段）",
      "The tag box edits the kind chosen above; the other kind keeps its own tags. Marker clips need a share under Media – their tags are the marker's primary or extra tag, and the filters apply to the marker's scene too. Exclude tags and the two switches count for all kinds.": "标签框编辑上面所选的类型；另一类型保留自己的标签。标记片段需要在“媒体”下设置比例——它们的标签是标记的主标签或附加标签，筛选条件同样适用于标记所在的场景。排除标签和两个开关对所有类型都有效。",
      "On tag pages, all chosen tags must match": "在标签页面上，所有选中的标签都必须匹配",
      "Minimum rating": "最低评分",
      "Only with favorite performers": "仅收藏的演员",
      favorites: "收藏演员",
      "Search tag…": "搜索标签…",
      "No tags found": "没有找到标签",
      "A playlist (from Stash UI)": "一个播放列表（来自 Stash UI）",
      Playlist: "播放列表",
      "A playlist": "一个播放列表",
      "No playlists yet": "还没有播放列表",
      "Stash UI's smart playlists: set filters in Scenes or Images there and press “Save as playlist”. The playlist decides – the filters below don't apply.": "Stash UI 的智能播放列表：在那里的场景或图片中设置筛选条件，然后点击“保存为播放列表”。由播放列表决定内容——下面的筛选条件不再生效。",
      "Only with performers": "仅包含演员",
      "All performers must be in it": "所有演员都必须出现",
      "Search performer…": "搜索演员…",
      "No performers found": "没有找到演员",
      "Resolution up to": "分辨率最高",
      "Videos at least": "视频至少",
      "any length": "不限时长",
      "1 min": "1 分钟",
      "5 min": "5 分钟",
      "20 min": "20 分钟",
      "A lower resolution runs smoother – 4K videos take the most.": "分辨率越低越流畅——4K 视频最吃性能。",
      "All folders": "所有文件夹",
      "Filter folders…": "筛选文件夹…",
      "Loading folders…": "正在加载文件夹…",
      "No folders found": "没有找到文件夹",
      "Without a choice, the whole library is used. Subfolders are always included. Numbers: images (I) and videos (V).": "不做选择时使用整个媒体库。始终包含子文件夹。数字：图片（I）和视频（V）。",
      "RedGifs share": "RedGifs 占比",
      "Niches, tags & creators": "分区、标签和创作者",
      "Search niches, tags, creators …": "搜索分区、标签、创作者 …",
      Niche: "分区",
      Niches: "分区",
      Tag: "标签",
      Tags: "标签",
      Creator: "创作者",
      Verified: "已认证",
      Trending: "热门",
      "Top of the week": "本周最佳",
      "Top of the month": "本月最佳",
      "Top (all time)": "历史最佳",
      Latest: "最新",
      "Sort order": "排序",
      Quality: "画质",
      "Saving (⬇ on hover or key D)": "保存（悬停时点 ⬇ 或按 D）",
      "Save location": "保存位置",
      "Everything in one folder": "全部放在一个文件夹",
      "By source (niche/tag/creator)": "按来源（分区/标签/创作者）",
      "By the clip's creator": "按片段的创作者",
      "Always saved in HD. If the save location is inside your Stash library, Stash scans the folder right away and the scene gets the link, title and the tag “RedGifs”.": "始终以高清保存。如果保存位置在你的 Stash 媒体库中，Stash 会立即扫描该文件夹，场景会获得链接、标题和“RedGifs”标签。",
      "Save the RedGifs clip under the mouse to Stash": "把鼠标下方的 RedGifs 片段保存到 Stash",
      "Hover over a RedGifs clip, then press D": "把鼠标悬停在 RedGifs 片段上，然后按 D",
      "Save to Stash (D)": "保存到 Stash（D）",
      "Open in Stash or on RedGifs": "在 Stash 或 RedGifs 中打开",
      "Open in Stash (Ctrl+click)": "在 Stash 中打开（Ctrl+点击）",
      "Open on RedGifs (Ctrl+click)": "在 RedGifs 上打开（Ctrl+点击）",
      "Already saved": "已保存过",
      "Already there": "已存在",
      Saved: "已保存",
      "Saved – Stash is still scanning, the scene will appear shortly": "已保存——Stash 仍在扫描，场景很快就会出现",
      "Saved, but importing into Stash failed:": "已保存，但导入 Stash 失败：",
      "Download failed:": "下载失败：",
      "Failed – try again": "失败——请重试",
      "Authentication failed": "身份验证失败",
      "creator not found": "未找到创作者",
      "not found": "未找到",
      "no Stash library configured": "未配置 Stash 媒体库",
      "no answer from the plugin backend": "插件后端没有响应",
      Preset: "预设",
      "Name for a new preset": "新预设的名称",
      "A preset of your own saves all settings, including source, filters and RedGifs.": "自己的预设会保存所有设置，包括来源、筛选和 RedGifs。",
      Save: "保存",
      Load: "加载",
      Delete: "删除",
      "None yet": "暂无",
      "Reset everything to defaults": "全部恢复默认",
      "Settings reset": "设置已重置",
      "Sleep timer": "睡眠定时",
      "Sleep timer ran out – good night": "睡眠定时结束——晚安",
      "The sleep timer stops with a fade-out and closes the storm tab.": "睡眠定时结束时会淡出停止，并关闭风暴标签页。",
      Afterwards: "之后",
      "This panel": "此面板",
      "Show the HUD in the storm tab": "在风暴标签页中显示状态栏",
      "Show item big": "放大显示项目",
      "Remove item": "移除项目",
      "Remove (right-click)": "移除（右键）",
      "Remove all items": "移除所有项目",
      "Stop everything (with fade-out)": "全部停止（淡出）",
      "Change layout": "切换布局",
      "Move item (chaos, pile)": "移动项目（混乱、堆叠）",
      "Scale item (chaos, pile)": "缩放项目（混乱、堆叠）",
      Click: "点击",
      "Ctrl+click": "Ctrl+点击",
      "Right-click": "右键",
      Drag: "拖动",
      "Mouse wheel": "鼠标滚轮",
      Space: "空格",
      "Volume ±5": "音量 ±5",
      Remove: "移除",
      Unknown: "未知",
      Off: "关闭",
      off: "关闭",
      auto: "自动",
      Max: "最大",
      Mixed: "混合",
      Random: "随机",
      Performer: "演员",
      Studio: "工作室",
      Group: "分组",
      Scene: "场景",
      Image: "图片",
      "Tag or folder": "标签或文件夹",
      "preview clips": "预览片段",
      endless: "无尽",
      "The storm tab detects tempo and beats itself (a few seconds per song), and the song loops. New items load ahead and appear exactly on the beat. Automatic: calm parts every bar, medium every 2 beats, loud every beat – drops right away. With pulse, the stage pumps on every beat; flash and shake come with the waves. “New wave every” doesn't apply then.": "风暴标签页会自行检测节奏和节拍（每首歌需要几秒钟），歌曲会循环播放。新项目会提前加载，并正好在节拍上出现。自动：安静部分每小节，中等每 2 拍，响亮每拍——高潮时立即出现。开启脉冲时，舞台随每个节拍跳动；闪光和震动随每一波出现。此时“每隔多久一波”不再生效。",
      "Loop videos (off = fade out after the end)": "循环播放视频（关闭 = 播放结束后淡出）",
      Rush: "冲击",
      any: "任意",
      "SD (faster)": "标清（更快）",
      "HD (sharper)": "高清（更清晰）",
      "Typing shows matching niches, tags and creators live – click (or ↑/↓ + Enter) to add them. Several are possible; one of them is picked at random per fetch. Without a choice you get trending. RedGifs only plays in the storm tab.": "输入时会实时显示匹配的分区、标签和创作者——点击（或 ↑/↓ + 回车）即可添加。可以添加多个，每次获取时随机选其中一个。不做选择时显示热门内容。RedGifs 只在风暴标签页中播放。",
      "HUD on/off": "状态栏 开/关",
      "Full videos at once": "同时播放的完整视频",
      "0 = automatic: Media Storm measures how quickly Stash still answers and plays as many full videos as the connection allows. Over plain HTTP, browsers keep only about 6 connections to one server – when they're all taken, Stash stops answering in this browser. Further videos play as preview clips (or show their cover).": "0 = 自动：媒体风暴会测量 Stash 的响应速度，并按连接允许的数量播放完整视频。在普通 HTTP 下，浏览器与同一服务器只保持大约 6 个连接——连接全部被占用时，Stash 在此浏览器中会停止响应。更多的视频将播放预览片段（或显示封面）。",
    },
    patterns: [
      ["Playlist “(.+)”", "播放列表“$1”"],
      ["(.+) \\((scenes|images)\\)", "$1（$2）"],
      ["up to (\\d+)p", "最高 $1p"],
      ["≥ (\\d+) min", "≥ $1 分钟"],
      ["(\\d+) performers", "$1 位演员"],
      ["On the beat (\\d+) new, max (\\d+) endless", "随节拍 · 每波 $1 个，最多 $2 个 · 无尽"],
      ["On the beat (\\d+) new, max (\\d+)", "随节拍 · 每波 $1 个，最多 $2 个"],
      ["Every (\\d+) s (\\d+) new, max (\\d+) endless", "每 $1 秒 · 每波 $2 个，最多 $3 个 · 无尽"],
      ["Every (\\d+) s (\\d+) new, max (\\d+)", "每 $1 秒 · 每波 $2 个，最多 $3 个"],
      ["(\\d+) % marker clips", "$1 % 标记片段"],
      ["Also active: (\\d+) tags? for scenes and images", "另外已启用：$1 个标签用于场景和图片"],
      ["Also active: (\\d+) tags? for marker clips", "另外已启用：$1 个标签用于标记片段"],
      ["(\\d+) marker tags? \\+sub", "$1 个标记标签（含子标签）"],
      ["(\\d+) marker tags?", "$1 个标记标签"],
      ["(\\d+) % of the videos", "占视频的 $1 %"],
      ["(\\d+) % videos, preview clips", "$1 % 视频，预览片段"],
      ["(\\d+) % videos", "$1 % 视频"],
      ["(\\d+) % images, (\\d+) % videos", "$1 % 图片，$2 % 视频"],
      ["(\\d+) %, (.+)", "$1 %，$2"],
      ["(.+?), frame (.+)", "$1，边框 $2"],
      ["Darkened (\\d+) %(.*)", "变暗 $1 %$2"],
      ["(\\d+) tags?", "$1 个标签"],
      ["without (\\d+)", "排除 $1 个"],
      ["from (★+)", "$1 起"],
      ["(\\d+) saved", "已保存 $1 个"],
      ["(\\d+) s", "$1 秒"],
      ["(\\d+) min", "$1 分钟"],
      ["level (\\d+)", "等级 $1"],
      ["every (\\d+) waves", "每 $1 波"],
      ["(\\d+) % of items", "占 $1 %"],
      ["(\\d+) px/s", "$1 像素/秒"],
      ["Volume (\\d+) ?%", "音量 $1%"],
      ["· (\\d+) Clips", "· $1 个片段"],
      ["Mood “(.+)”", "氛围“$1”"],
      ["Preset “(.+)” deleted", "预设“$1”已删除"],
      ["Preset “(.+)” loaded", "预设“$1”已加载"],
      ["Preset “(.+)” saved", "预设“$1”已保存"],
      ["Song “(.+)” chosen", "已选择歌曲“$1”"],
      ["On the beat: (.+) BPM", "随节拍：$1 BPM"],
      ["On the beat: detecting beats in “(.+)” …", "随节拍：正在检测“$1”的节拍 …"],
      ["Imported into Stash ✓ \\((.+?) #(\\d+)\\)", "已导入 Stash ✓（$1 #$2）"],
      ["Error while loading: (.+)", "加载出错：$1"],
      ["Background error: (.+)", "背景出错：$1"],
      ["Error: (.+)", "错误：$1"],
      ["Download failed: (.+)", "下载失败：$1"],
      ["Saved, but importing into Stash failed: (.+)", "已保存，但导入 Stash 失败：$1"],
      ["GraphQL error: (.+)", "GraphQL 错误：$1"],
      ["Media Storm (\\d[\\d.]*)", "媒体风暴 $1"],
      ["([\\d.,]+) Tsd\\.", "$1 千"],
      ["([\\d.,]+) Mio\\.", "$1 百万"],
    ],
  };
})();
