// Media Storm in French. Loaded before mediaStorm.js; the English text as shown is the key.
// Patterns catch texts with numbers or names ($1, $2 … = the parts in brackets, translated too if they
// are in `texts`). The language follows Stash UI's choice, otherwise Stash's interface language.
(function () {
  window.MediaStormLocales = window.MediaStormLocales || {};
  window.MediaStormLocales["fr"] = {
    sep: ", ",
    texts: {
      "Media Storm": "Media Storm",
      "Storm": "Storm",
      "Ready": "Prêt",
      "Running": "En cours",
      "Paused": "En pause",
      "Stopped": "Arrêté",
      "starts in its own tab": "démarre dans son propre onglet",
      "Running in the storm tab": "En cours dans l'onglet storm",
      "Start": "Démarrer",
      "Stop": "Arrêter",
      "Restart": "Redémarrer",
      "Pause": "Pause",
      "Pause / resume": "Pause / reprise",
      "Pause / resume (Space)": "Pause / reprise (Espace)",
      "Next wave": "Vague suivante",
      "Next wave now (N)": "Vague suivante maintenant (N)",
      "Next wave right away": "Vague suivante tout de suite",
      "New wave": "Nouvelle vague",
      "Reroll background": "Retirer l'arrière-plan",
      "Reroll background (B)": "Retirer l'arrière-plan (B)",
      "Close (Esc)": "Fermer (Échap)",
      "Close panel": "Fermer le panneau",
      "Stop (Esc)": "Arrêter (Échap)",
      "Settings (S)": "Paramètres (S)",
      "Settings": "Paramètres",
      "Fullscreen (F)": "Plein écran (F)",
      "Fullscreen": "Plein écran",
      "Fullscreen not allowed": "Plein écran non autorisé",
      "Liquid glass": "Verre liquide",
      "Back": "Retour",
      "Back to the overview (Esc)": "Retour à l'aperçu (Échap)",
      "Hotkeys & mouse": "Raccourcis et souris",
      "Expand/collapse": "Développer/réduire",
      "Click or press a key for sound": "Cliquez ou appuyez sur une touche pour activer le son",
      "A freshly opened storm tab may only play sound after a click or key press.": "Un onglet storm tout juste ouvert ne peut parfois jouer du son qu'après un clic ou une touche.",
      "Nothing found": "Rien trouvé",
      "With these filters there are no images or videos. Loosen tags, folders or rating – or reset everything.": "Avec ces filtres, il n'y a ni images ni vidéos. Assouplissez étiquettes, dossiers ou note – ou réinitialisez tout.",
      "Reset filters": "Réinitialiser les filtres",
      "Filters reset – whole library": "Filtres réinitialisés – toute la bibliothèque",
      "No media found for this source/filter": "Aucun média trouvé pour cette source/ce filtre",
      "First wave loading …": "Chargement de la première vague …",
      "Searching …": "Recherche …",
      "Error while loading:": "Erreur de chargement :",
      "Background error:": "Erreur d'arrière-plan :",
      "GraphQL error:": "Erreur GraphQL :",
      "Pop-up blocked – please allow pop-ups for Stash": "Fenêtre bloquée – autorisez les pop-ups pour Stash",
      "Mood": "Ambiance",
      "Next mood": "Ambiance suivante",
      "Default": "Par défaut",
      "Chaos as usual": "Chaos habituel",
      "Chill": "Chill",
      "Pile, calm, breathing": "Pile, calme, respirant",
      "Fast, full, shaking": "Rapide, plein, tremblant",
      "Gallery": "Galerie",
      "Mosaic, tidy": "Mosaïque, ordonnée",
      "Cinema": "Cinéma",
      "Spotlight, videos only": "Projecteur, vidéos uniquement",
      "Trip": "Trip",
      "Spiral, colors, 3D": "Spirale, couleurs, 3D",
      "Ticker": "Bandeau défilant",
      "Polaroids drift by": "Des Polaroids défilent",
      "Rain": "Pluie",
      "Falls through from the top": "Tombe d'en haut",
      "Manga": "Manga",
      "Ink, halftone, impact": "Encre, trame, impact",
      "Neon": "Néon",
      "Glow, glitch, beat": "Lueur, glitch, rythme",
      "Tempo": "Tempo",
      "On the beat": "Sur le rythme",
      "Media": "Médias",
      "Sound": "Son",
      "Layout": "Disposition",
      "Layout:": "Disposition :",
      "Effects": "Effets",
      "Background": "Arrière-plan",
      "Source & filters": "Source et filtres",
      "Folders": "Dossiers",
      "RedGifs": "RedGifs",
      "My presets": "Mes préréglages",
      "New wave every": "Nouvelle vague toutes les",
      "Every": "Toutes les",
      "Items per wave": "Éléments par vague",
      "First wave (right away)": "Première vague (tout de suite)",
      "At most at once": "Maximum en même temps",
      "Items / Maximum": "Éléments / Maximum",
      "Endless – replace the oldest items instead of stopping": "Sans fin – remplace les plus anciens éléments au lieu de s'arrêter",
      "Waves on the beat of a song": "Vagues sur le rythme d'une chanson",
      "Choose song …": "Choisir une chanson …",
      "No song yet": "Pas encore de chanson",
      "No song chosen": "Aucune chanson choisie",
      "Song volume": "Volume de la chanson",
      "Every 2 beats": "Tous les 2 temps",
      "Every bar (4 beats)": "Chaque mesure (4 temps)",
      "Every 2 bars": "Toutes les 2 mesures",
      "On every beat": "À chaque temps",
      "Couldn't save the song (storage blocked?)": "Impossible d'enregistrer la chanson (stockage bloqué ?)",
      "On the beat: click or press a key to start the music": "Sur le rythme : cliquez ou appuyez sur une touche pour lancer la musique",
      "On the beat: couldn't read the song": "Sur le rythme : impossible de lire la chanson",
      "On the beat: no song chosen yet (panel → On the beat) – waves run by time": "Sur le rythme : aucune chanson choisie (panneau → Sur le rythme) – les vagues suivent le temps",
      "Images": "Images",
      "Videos": "Vidéos",
      "Mix": "Mélange",
      "Video source": "Source vidéo",
      "Full video": "Vidéo entière",
      "Preview clip (lighter)": "Extrait d'aperçu (plus léger)",
      "Image quality": "Qualité d'image",
      "Thumbnail (faster)": "Miniature (plus rapide)",
      "Original": "Original",
      "Random start": "Départ aléatoire",
      "Random start point in the video": "Point de départ aléatoire dans la vidéo",
      "Ken Burns zoom on images": "Zoom Ken Burns sur les images",
      "Volume": "Volume",
      "Audible": "Audible",
      "all videos": "toutes les vidéos",
      "All videos": "Toutes les vidéos",
      "under the mouse": "sous la souris",
      "Only under the mouse": "Seulement sous la souris",
      "newest video": "vidéo la plus récente",
      "Only the newest video": "Seulement la vidéo la plus récente",
      "muted": "muet",
      "Muted": "Muet",
      "Automatic by loudness": "Automatique selon le volume sonore",
      "Chaos": "Chaos",
      "Pile": "Pile",
      "Grid": "Grille",
      "Mosaic": "Mosaïque",
      "Spotlight": "Projecteur",
      "Spiral": "Spirale",
      "Scattered everywhere. Drag to move, mouse wheel to scale.": "Éparpillé partout. Glissez pour déplacer, molette pour redimensionner.",
      "Like photos on a table, heaped towards the middle.": "Comme des photos sur une table, empilées vers le milieu.",
      "Fixed cells that fill the whole screen.": "Des cellules fixes qui remplissent tout l'écran.",
      "Pinboard columns: new items come in at the top, the rest slides down.": "Colonnes de tableau d'affichage : les nouveaux éléments arrivent en haut, le reste glisse vers le bas.",
      "The newest item big in the middle, the older ones in a circle around it.": "L'élément le plus récent en grand au milieu, les plus anciens en cercle autour.",
      "Sunflower spiral with the newest item in the middle – every wave turns everything further.": "Spirale en tournesol avec l'élément le plus récent au milieu – chaque vague fait tourner le tout un peu plus.",
      "Lanes from right to left. Items that have passed make room for new ones.": "Des voies de droite à gauche. Les éléments qui sont passés font place aux nouveaux.",
      "Falls through from the top. At the bottom, items make room for new ones.": "Tombe d'en haut. En bas, les éléments font place aux nouveaux.",
      "Avoid overlap – free spots first": "Éviter les chevauchements – places libres d'abord",
      "Size min": "Taille min.",
      "Size max": "Taille max.",
      "Rotation": "Rotation",
      "Spacing": "Espacement",
      "Columns": "Colonnes",
      "Speed": "Vitesse",
      "Frame": "Cadre",
      "Soft": "Doux",
      "None": "Aucun",
      "Polaroid": "Polaroid",
      "Circle": "Cercle",
      "Square": "Carré",
      "Shape": "Forme",
      "Format": "Format",
      "Landscape 16:9": "Paysage 16:9",
      "Portrait 3:4": "Portrait 3:4",
      "Appear": "Apparition",
      "Zoom": "Zoom",
      "Fade in": "Fondu en entrée",
      "Fade in and out": "Fondu en entrée et sortie",
      "Slam": "Claque",
      "Flip": "Retournement",
      "Fall": "Chute",
      "Spin": "Rotation",
      "Glitch start": "Départ en glitch",
      "Motion": "Mouvement",
      "Drift": "Dérive",
      "Breathe": "Respiration",
      "Wobble": "Tremblement",
      "Hold still": "Immobile",
      "Pulse": "Pulsation",
      "Color rush": "Ruée de couleurs",
      "Glitch": "Glitch",
      "Blending": "Fusion",
      "Normal": "Normal",
      "Double exposure": "Double exposition",
      "Negative": "Négatif",
      "Negative rush": "Ruée de négatif",
      "Texture": "Texture",
      "Film grain": "Grain de film",
      "Halftone": "Trame",
      "Vignette": "Vignettage",
      "3D depth – parallax with the mouse": "Profondeur 3D – parallaxe avec la souris",
      "Reflection": "Reflet",
      "Reflection under every item": "Reflet sous chaque élément",
      "Shake": "Secousse",
      "Flash": "Flash",
      "The flash is gentle and comes at most once per wave.": "Le flash est doux et n'arrive qu'une fois par vague au maximum.",
      "Just zoom and fade": "Seulement zoom et fondu",
      "Darken": "Assombrir",
      "Blur": "Flou",
      "soft": "doux",
      "rerolls itself": "se retire tout seul",
      "New background": "Nouvel arrière-plan",
      "Reroll automatically": "Retirer automatiquement",
      "On every new wave": "À chaque nouvelle vague",
      "Artwork in the design": "Illustrations dans le design",
      "Show images in the panel and at the start": "Afficher des images dans le panneau et au démarrage",
      "e.g. Artwork": "p. ex. Artwork",
      "Uses images and scene screenshots with this tag and from folders with the same name. Click the cover for the next image.": "Utilise les images et captures de scènes portant cette étiquette ainsi que celles des dossiers du même nom. Cliquez sur la couverture pour l'image suivante.",
      "Next image": "Image suivante",
      "No background images found (tag “background”)": "Aucune image d'arrière-plan trouvée (étiquette « background »)",
      "The Random Backgrounds plugin is not active": "Le plugin Random Backgrounds n'est pas actif",
      "plugin not active": "plugin non actif",
      "Source": "Source",
      "Whole library": "Toute la bibliothèque",
      "Current page": "Page actuelle",
      "Current page (performer/tag/…)": "Page actuelle (interprète/étiquette/…)",
      "“Current page” uses the performer, tag, studio, gallery or group page you start from. On tag pages, your own tags always all have to match.": "« Page actuelle » utilise la page d'interprète, d'étiquette, de studio, de galerie ou de groupe d'où vous partez. Sur les pages d'étiquette, vos propres étiquettes doivent toutes correspondre.",
      "Not a performer/tag/studio/gallery/group page – using the whole library": "Pas une page d'interprète/étiquette/studio/galerie/groupe – utilisation de toute la bibliothèque",
      "Only with tags": "Seulement avec les étiquettes",
      "Exclude tags": "Exclure des étiquettes",
      "Marker clips": "Clips de marqueurs",
      "Marker clips are the short moments you marked in your scenes. This share of the videos plays them (only the marked part, looping) instead of whole scenes. Choose which markers under Source & filters.": "Les clips de marqueurs sont les courts instants que vous avez marqués dans vos scènes. Cette part des vidéos les joue (seulement la partie marquée, en boucle) au lieu de scènes entières. Choisissez quels marqueurs sous Source et filtres.",
      "Only marker clips with tags": "Seulement les clips de marqueurs avec étiquettes",
      "Needs a share of marker clips under Media. Primary or extra tag of the marker; the filters above apply to the marker's scene.": "Nécessite une part de clips de marqueurs sous Médias. Étiquette principale ou supplémentaire du marqueur ; les filtres ci-dessus s'appliquent à la scène du marqueur.",
      "All tags must match": "Toutes les étiquettes doivent correspondre",
      "Including sub-tags (recursive)": "Inclure les sous-étiquettes (récursif)",
      "On tag pages, all chosen tags must match": "Sur les pages d'étiquette, toutes les étiquettes choisies doivent correspondre",
      "Minimum rating": "Note minimale",
      "Only with favorite performers": "Seulement avec des interprètes favoris",
      "favorites": "favoris",
      "Search tag…": "Rechercher une étiquette…",
      "No tags found": "Aucune étiquette trouvée",
      "A playlist (from Stash UI)": "Une playlist (de Stash UI)",
      "Playlist": "Playlist",
      "A playlist": "Une playlist",
      "No playlists yet": "Pas encore de playlists",
      "Stash UI's smart playlists: set filters in Scenes or Images there and press “Save as playlist”. The playlist decides – the filters below don't apply.": "Les playlists intelligentes de Stash UI : réglez des filtres dans Scènes ou Images là-bas et appuyez sur « Enregistrer comme playlist ». La playlist décide – les filtres ci-dessous ne s'appliquent pas.",
      "Only with performers": "Seulement avec les interprètes",
      "All performers must be in it": "Tous les interprètes doivent y figurer",
      "Search performer…": "Rechercher un interprète…",
      "No performers found": "Aucun interprète trouvé",
      "Resolution up to": "Résolution jusqu'à",
      "Videos at least": "Vidéos d'au moins",
      "any length": "toutes durées",
      "1 min": "1 min",
      "5 min": "5 min",
      "20 min": "20 min",
      "A lower resolution runs smoother – 4K videos take the most.": "Une résolution plus basse est plus fluide – les vidéos 4K sont les plus gourmandes.",
      "All folders": "Tous les dossiers",
      "Filter folders…": "Filtrer les dossiers…",
      "Loading folders…": "Chargement des dossiers…",
      "No folders found": "Aucun dossier trouvé",
      "Without a choice, the whole library is used. Subfolders are always included. Numbers: images (I) and videos (V).": "Sans choix, toute la bibliothèque est utilisée. Les sous-dossiers sont toujours inclus. Chiffres : images (I) et vidéos (V).",
      "RedGifs share": "Part de RedGifs",
      "Niches, tags & creators": "Niches, étiquettes et créateurs",
      "Search niches, tags, creators …": "Rechercher niches, étiquettes, créateurs …",
      "Niche": "Niche",
      "Niches": "Niches",
      "Tag": "Étiquette",
      "Tags": "Étiquettes",
      "Creator": "Créateur",
      "Verified": "Vérifié",
      "Trending": "Tendances",
      "Top of the week": "Top de la semaine",
      "Top of the month": "Top du mois",
      "Top (all time)": "Top (depuis toujours)",
      "Latest": "Récents",
      "Sort order": "Ordre de tri",
      "Quality": "Qualité",
      "Saving (⬇ on hover or key D)": "Enregistrement (⬇ au survol ou touche D)",
      "Save location": "Emplacement d'enregistrement",
      "Everything in one folder": "Tout dans un seul dossier",
      "By source (niche/tag/creator)": "Par source (niche/étiquette/créateur)",
      "By the clip's creator": "Par créateur du clip",
      "Always saved in HD. If the save location is inside your Stash library, Stash scans the folder right away and the scene gets the link, title and the tag “RedGifs”.": "Toujours enregistré en HD. Si l'emplacement est dans votre bibliothèque Stash, Stash analyse tout de suite le dossier et la scène reçoit le lien, le titre et l'étiquette « RedGifs ».",
      "Save the RedGifs clip under the mouse to Stash": "Enregistrer dans Stash le clip RedGifs sous la souris",
      "Hover over a RedGifs clip, then press D": "Survolez un clip RedGifs puis appuyez sur D",
      "Save to Stash (D)": "Enregistrer dans Stash (D)",
      "Open in Stash or on RedGifs": "Ouvrir dans Stash ou sur RedGifs",
      "Open in Stash (Ctrl+click)": "Ouvrir dans Stash (Ctrl+clic)",
      "Open on RedGifs (Ctrl+click)": "Ouvrir sur RedGifs (Ctrl+clic)",
      "Already saved": "Déjà enregistré",
      "Already there": "Déjà là",
      "Saved": "Enregistré",
      "Saved – Stash is still scanning, the scene will appear shortly": "Enregistré – Stash analyse encore, la scène apparaîtra sous peu",
      "Saved, but importing into Stash failed:": "Enregistré, mais l'import dans Stash a échoué :",
      "Download failed:": "Le téléchargement a échoué :",
      "Failed – try again": "Échec – réessayez",
      "Authentication failed": "Échec de l'authentification",
      "creator not found": "créateur introuvable",
      "not found": "introuvable",
      "no Stash library configured": "aucune bibliothèque Stash configurée",
      "no answer from the plugin backend": "pas de réponse du backend du plugin",
      "Preset": "Préréglage",
      "Name for a new preset": "Nom du nouveau préréglage",
      "A preset of your own saves all settings, including source, filters and RedGifs.": "Un préréglage personnel enregistre tous les réglages, y compris source, filtres et RedGifs.",
      "Save": "Enregistrer",
      "Load": "Charger",
      "Delete": "Supprimer",
      "None yet": "Aucun pour l'instant",
      "Reset everything to defaults": "Tout remettre par défaut",
      "Settings reset": "Réglages réinitialisés",
      "Sleep timer": "Minuterie de veille",
      "Sleep timer ran out – good night": "La minuterie de veille est écoulée – bonne nuit",
      "The sleep timer stops with a fade-out and closes the storm tab.": "La minuterie de veille s'arrête avec un fondu et ferme l'onglet storm.",
      "Afterwards": "Ensuite",
      "This panel": "Ce panneau",
      "Show the HUD in the storm tab": "Afficher le HUD dans l'onglet storm",
      "Show item big": "Afficher l'élément en grand",
      "Remove item": "Retirer l'élément",
      "Remove (right-click)": "Retirer (clic droit)",
      "Remove all items": "Retirer tous les éléments",
      "Stop everything (with fade-out)": "Tout arrêter (avec fondu)",
      "Change layout": "Changer de disposition",
      "Move item (chaos, pile)": "Déplacer un élément (chaos, pile)",
      "Scale item (chaos, pile)": "Redimensionner un élément (chaos, pile)",
      "Click": "Clic",
      "Ctrl+click": "Ctrl+clic",
      "Right-click": "Clic droit",
      "Drag": "Glisser",
      "Mouse wheel": "Molette",
      "Space": "Espace",
      "Volume ±5": "Volume ±5",
      "Remove": "Retirer",
      "Unknown": "Inconnu",
      "Off": "Désactivé",
      "off": "désactivé",
      "auto": "auto",
      "Max": "Max",
      "Mixed": "Mixte",
      "Random": "Aléatoire",
      "Performer": "Interprète",
      "Studio": "Studio",
      "Group": "Groupe",
      "Scene": "Scène",
      "Image": "Image",
      "Tag or folder": "Étiquette ou dossier",
      "preview clips": "extraits d'aperçu",
      "endless": "sans fin",
      "The storm tab detects tempo and beats itself (a few seconds per song), and the song loops. New items load ahead and appear exactly on the beat. Automatic: calm parts every bar, medium every 2 beats, loud every beat – drops right away. With pulse, the stage pumps on every beat; flash and shake come with the waves. “New wave every” doesn't apply then.": "L'onglet storm détecte lui-même le tempo et les temps (quelques secondes par chanson), et la chanson tourne en boucle. Les nouveaux éléments se chargent à l'avance et apparaissent exactement sur le temps. Automatique : passages calmes à chaque mesure, moyens tous les 2 temps, forts à chaque temps – les drops tout de suite. Avec la pulsation, la scène pulse à chaque temps ; flash et secousse viennent avec les vagues. « Nouvelle vague toutes les » ne s'applique alors pas.",
      "Loop videos (off = fade out after the end)": "Vidéos en boucle (désactivé = fondu après la fin)",
      "Rush": "Ruée",
      "any": "tous",
      "SD (faster)": "SD (plus rapide)",
      "HD (sharper)": "HD (plus net)",
      "Typing shows matching niches, tags and creators live – click (or ↑/↓ + Enter) to add them. Several are possible; one of them is picked at random per fetch. Without a choice you get trending. RedGifs only plays in the storm tab.": "La saisie affiche en direct les niches, étiquettes et créateurs correspondants – cliquez (ou ↑/↓ + Entrée) pour les ajouter. Plusieurs sont possibles ; l'un d'eux est tiré au hasard à chaque récupération. Sans choix, vous obtenez les tendances. RedGifs ne joue que dans l'onglet storm.",
      "HUD on/off": "HUD activé/désactivé",
      "Full videos at once": "Vidéos entières en même temps",
      "0 = automatic: Media Storm measures how quickly Stash still answers and plays as many full videos as the connection allows. Over plain HTTP, browsers keep only about 6 connections to one server – when they're all taken, Stash stops answering in this browser. Further videos play as preview clips (or show their cover).": "0 = automatique : Media Storm mesure la rapidité avec laquelle Stash répond encore et lit autant de vidéos entières que la connexion le permet. En HTTP simple, les navigateurs ne gardent qu'environ 6 connexions vers un serveur – quand elles sont toutes prises, Stash ne répond plus dans ce navigateur. Les autres vidéos jouent comme extraits d'aperçu (ou montrent leur couverture).",
    },
    patterns: [
      ["Playlist “(.+)”", "Playlist « $1 »"],
      ["(.+) \\((scenes|images)\\)", "$1 ($2)"],
      ["up to (\\d+)p", "jusqu'à $1p"],
      ["≥ (\\d+) min", "≥ $1 min"],
      ["(\\d+) performers", "$1 interprètes"],
      ["On the beat (\\d+) new, max (\\d+) endless", "Sur le rythme · $1 nouveaux, max. $2 · sans fin"],
      ["On the beat (\\d+) new, max (\\d+)", "Sur le rythme · $1 nouveaux, max. $2"],
      ["Every (\\d+) s (\\d+) new, max (\\d+) endless", "Toutes les $1 s · $2 nouveaux, max. $3 · sans fin"],
      ["Every (\\d+) s (\\d+) new, max (\\d+)", "Toutes les $1 s · $2 nouveaux, max. $3"],
      ["(\\d+) % marker clips", "$1 % de clips de marqueurs"],
      ["(\\d+) marker tags? \\+sub", "$1 étiquettes de marqueurs (avec sous-étiquettes)"],
      ["(\\d+) marker tags?", "$1 étiquettes de marqueurs"],
      ["(\\d+) % of the videos", "$1 % des vidéos"],
      ["(\\d+) % videos, preview clips", "$1 % de vidéos, extraits d'aperçu"],
      ["(\\d+) % videos", "$1 % de vidéos"],
      ["(\\d+) % images, (\\d+) % videos", "$1 % d'images, $2 % de vidéos"],
      ["(\\d+) %, (.+)", "$1 %, $2"],
      ["(.+?), frame (.+)", "$1, cadre $2"],
      ["Darkened (\\d+) %(.*)", "Assombri de $1 %$2"],
      ["(\\d+) tags?", "$1 étiquettes"],
      ["without (\\d+)", "sans $1"],
      ["from (★+)", "à partir de $1"],
      ["(\\d+) saved", "$1 enregistrés"],
      ["(\\d+) s", "$1 s"],
      ["(\\d+) min", "$1 min"],
      ["level (\\d+)", "niveau $1"],
      ["every (\\d+) waves", "toutes les $1 vagues"],
      ["(\\d+) % of items", "$1 % des éléments"],
      ["(\\d+) px/s", "$1 px/s"],
      ["Volume (\\d+) ?%", "Volume $1 %"],
      ["· (\\d+) Clips", "· $1 clips"],
      ["Mood “(.+)”", "Ambiance « $1 »"],
      ["Preset “(.+)” deleted", "Préréglage « $1 » supprimé"],
      ["Preset “(.+)” loaded", "Préréglage « $1 » chargé"],
      ["Preset “(.+)” saved", "Préréglage « $1 » enregistré"],
      ["Song “(.+)” chosen", "Chanson « $1 » choisie"],
      ["On the beat: (.+) BPM", "Sur le rythme : $1 BPM"],
      ["On the beat: detecting beats in “(.+)” …", "Sur le rythme : détection des temps dans « $1 » …"],
      ["Imported into Stash ✓ \\((.+?) #(\\d+)\\)", "Importé dans Stash ✓ ($1 #$2)"],
      ["Error while loading: (.+)", "Erreur de chargement : $1"],
      ["Background error: (.+)", "Erreur d'arrière-plan : $1"],
      ["Error: (.+)", "Erreur : $1"],
      ["Download failed: (.+)", "Le téléchargement a échoué : $1"],
      ["Saved, but importing into Stash failed: (.+)", "Enregistré, mais l'import dans Stash a échoué : $1"],
      ["GraphQL error: (.+)", "Erreur GraphQL : $1"],
      ["Media Storm (\\d[\\d.]*)", "Media Storm $1"],
      ["([\\d.,]+) Tsd\\.", "$1 k"],
      ["([\\d.,]+) Mio\\.", "$1 M"],
    ],
  };
})();
